### ISSUE TITLE
Dirty SIGINT exit

### ISSUE THREAD

**Issue by ChrisOelmueller** [unknown-horizons/unknown-horizons#1974]
- start UH
- click on Settings
- send SIGINT (via ctrl-C)

``` pytb
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/widgets/listbox.py", line 38, in getNumberOfElements
    def getNumberOfElements(self):
  File "./run_uh.py", line 237, in exithandler
    sys.exit(exitcode)
SystemExit: 130

Traceback (most recent call last):
  File "./run_uh.py", line 475, in <module>
    main()
  File "./run_uh.py", line 284, in main
    ret = horizons.main.start(options)
  File "/home/eoc/UH/unknown-horizons/horizons/main.py", line 290, in start
    horizons.globals.fife.run()
  File "/home/eoc/UH/unknown-horizons/horizons/engine/engine.py", line 270, in run
    self.loop()
  File "/home/eoc/UH/unknown-horizons/horizons/engine/engine.py", line 279, in loop
    self.engine.pump()
  File "/usr/lib/python2.7/site-packages/fife/fife.py", line 2167, in pump
    return _fife.Engine_pump(self)
RuntimeError: Caught a director exception
```

**Comment by CrafterSvK** [comment]
This problem still exists

**Comment by AndyMender** [comment]
After refactoring to Python3 the problem is still there. An example solution is available: http://stackoverflow.com/questions/1112343/how-do-i-capture-sigint-in-python#1112350

@LinuxDonald, would you like me to have a look at this?

**Comment by LinuxDonald** [comment]
Please do it :-)

**Comment by AndyMender** [comment]
The current traceback is as follows:
```
^C
Oh my god! They killed UH. 
You bastards!
Traceback (most recent call last):
  File "run_uh.py", line 372, in <module>
    main()
  File "run_uh.py", line 182, in main
    ret = horizons.main.start(options)
  File "/home/andy/uh_devel/unknown-horizons/horizons/main.py", line 251, in start
    horizons.globals.fife.run()
  File "/home/andy/uh_devel/unknown-horizons/horizons/engine/engine.py", line 277, in run
    self.loop()
  File "/home/andy/uh_devel/unknown-horizons/horizons/engine/engine.py", line 284, in loop
    self.engine.pump()
RuntimeError: Caught a director exception
```
I silenced it by handling the `RuntimeError` exception in Python, but I feel it might hide a deeper issue on the line Python <> FIFE. @helios2000, any ideas?

**Comment by AndyMender** [comment]
Traceback when SIGINT is sent during game loading:
```pytb
^C
Oh my god! They killed UH. 
You bastards!
Traceback (most recent call last):
 File "/usr/lib64/python3.5/site-packages/fife/extensions/fife_timer.py", line 125, in updateEvent
    self._callback()
 File "/usr/lib64/python3.5/site-packages/fife/extensions/pychan/tools.py", line 94, in real_callback
    callback(*args,**kwargs)
 File "/usr/lib64/python3.5/site-packages/fife/extensions/pychan/events.py", line 194, in delayed_f
    f( event )
 File "/usr/lib64/python3.5/site-packages/fife/extensions/pychan/events.py", line 374, in captured_f
    tools.applyOnlySuitable(self_ref().callbacks[group_name][event_name],event=event,widget=self_ref().widget_ref())
 File "/usr/lib64/python3.5/site-packages/fife/extensions/pychan/tools.py", line 71, in applyOnlySuitable
    return func(*args,**kwargs)
 File "/home/andy/uh_devel/unknown-horizons/horizons/gui/gui.py", line 157, in load_game
    horizons.main.start_singleplayer(options)
 File "/home/andy/uh_devel/unknown-horizons/horizons/main.py", line 347, in start_singleplayer
    _modules.session.load(options)
 File "/home/andy/uh_devel/unknown-horizons/horizons/spsession.py", line 45, in load
    super(SPSession, self).load(*args, **kwargs)
 File "/home/andy/uh_devel/unknown-horizons/horizons/session.py", line 250, in load
    self.world._init(savegame_db, options.force_player_id, disasters_enabled=options.disasters_enabled)
 File "/home/andy/uh_devel/unknown-horizons/horizons/world/__init__.py", line 164, in _init
    self.load_raw_map(savegame_db)
 File "/home/andy/uh_devel/unknown-horizons/horizons/world/__init__.py", line 265, in load_raw_map
    island = Island(savegame_db, islandid, self.session, preview=preview)
 File "/home/andy/uh_devel/unknown-horizons/horizons/world/island.py", line 97, in __init__
    settlement = Settlement.load(db, settlement_id, self.session, self)
 File "/home/andy/uh_devel/unknown-horizons/horizons/world/settlement.py", line 188, in load
    building = load_building(session, db, building_type, building_id)
 File "/home/andy/uh_devel/unknown-horizons/horizons/world/__init__.py", line 734, in load_building
    return Entities.buildings[typeid].load(session, db, worldid)
 File "/home/andy/uh_devel/unknown-horizons/horizons/world/ingametype.py", line 56, in load
    super(cls, self).load(db, worldid)
 File "/home/andy/uh_devel/unknown-horizons/horizons/world/building/settler.py", line 99, in load
    super(Settler, self).load(db, worldid)
 File "/home/andy/uh_devel/unknown-horizons/horizons/world/building/buildingresourcehandler.py", line 47, in load
    super(BuildingResourceHandler, self).load(db, worldid)
 File "/home/andy/uh_devel/unknown-horizons/horizons/world/resourcehandler.py", line 86, in load
    super(ResourceHandler, self).load(db, worldid)
 File "/home/andy/uh_devel/unknown-horizons/horizons/world/building/building.py", line 160, in load
    self.__init(remaining_ticks_of_month=remaining_ticks_of_month)
 File "/home/andy/uh_devel/unknown-horizons/horizons/world/building/building.py", line 96, in __init
    rotation=self.rotation, action_set_id=self._action_set_id, world_id=str(self.worldid))
 File "/home/andy/uh_devel/unknown-horizons/horizons/world/building/building.py", line 286, in getInstance
    cls._fife_object,
 File "/home/andy/uh_devel/unknown-horizons/horizons/world/ingametype.py", line 183, in _fife_object
    self._loadObject()
 File "/home/andy/uh_devel/unknown-horizons/horizons/world/building/__init__.py", line 89, in _loadObject
    cls._do_load(all_action_sets, action_set, action_id)
 File "/home/andy/uh_devel/unknown-horizons/horizons/world/building/__init__.py", line 152, in _do_load
    anim = horizons.globals.fife.animationloader.loadResource(path)
 File "/home/andy/uh_devel/unknown-horizons/horizons/util/loaders/sqliteanimationloader.py", line 63, in loadResource
    img = horizons.globals.fife.imagemanager.load(f)
 File "run_uh.py", line 134, in exithandler
    sys.exit(exitcode)
SystemExit: 130
```
Still, everything boils down to the `exithandler` function in run_uh.py that lets the traceback through.

**Comment by AndyMender** [comment]
For whatever reason the dirty `SIGINT` traceback cannot be captured either via a log file or handling `sys.excepthook` (which is done anyway by the `excepthook_creator` in debug mode). I tried every possible means of redirecting I could come up with and the only thing that actually "works" is simply silencing all traceback via `sys.tracebacklimit = 0`. Granted, this is done in a way that in debug mode the traceback and any errors will still be captured in a log file.
