### ISSUE TITLE
Game crash when selecting random map

### ISSUE THREAD

**Issue by ChrisOelmueller** [unknown-horizons/unknown-horizons#2193]
[reported by **grimsonjr**] (http://forum.unknown-horizons.org/viewtopic.php?t=7218)

Hi!
My game crashes when just selecting the "generate random map" option in the single player menu.

```pytb

Traceback (most recent call last):
  File "run_uh.py", line 473, in <module>
    main()
  File "run_uh.py", line 283, in main
    ret = horizons.main.start(options)
  File "C:\Program Files (x86)\Unknown Horizons\horizons\main.py", line 294, in start
    horizons.globals.fife.run()
  File "C:\Program Files (x86)\Unknown Horizons\horizons\engine\engine.py", line 257, in run
    self.loop()
  File "C:\Program Files (x86)\Unknown Horizons\horizons\engine\engine.py", line 269, in loop
    f()
  File "C:\Program Files (x86)\Unknown Horizons\horizons\extscheduler.py", line 72, in tick
    obj.callback()
  File "C:\Program Files (x86)\Unknown Horizons\horizons\gui\modules\singleplayermenu.py", line 348, in _poll_preview_process
    self._map_preview.draw_data(data)
  File "C:\Program Files (x86)\Unknown Horizons\horizons\gui\widgets\minimap.py", line 205, in draw_data
    for x, y, r, g, b in json.loads(data):
  File "C:\Program Files (x86)\Unknown Horizons\python\lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Unknown Horizons\python\lib\json\decoder.py", line 368, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 4 column 1 (char 410737 - 410842)
```

Seems to have something to do with the "generate preview" function, but I don't know.

**Comment by LinuxDonald** [comment]
For me it ist working.

**Comment by LinuxDonald** [comment]
Reopen it when it crashing again.

**Comment by stubb** [comment]
This is only hack fixed, so this issue shouldn't be closed yet.
