### ISSUE TITLE
self-created map can't be played without the corresponding map file itself

### ISSUE THREAD

**Issue by myrdd** [unknown-horizons/unknown-horizons#2263]
If you create your own map with the map editor, start a game with it, save that game and then delete the map file (e.g. `maps/test.sqlite`), the savegame can't be played anymore.
1. Start UH
2. Create a new map in the map editor, save and exit editor (there may be only water)
3. Create a new game (free play) and save that game.
4. Close UH
5. Delete the map (not the game!) in `UH_folder/maps/`
6. Start UH and load the saved game.
7. I get the following message:

![](http://up.unknown-horizons.org/f/?a=v&id=618&n=bug_map_deleted__error_message.jpg)

and this is the traceback I get:

``` python
Failed to load /home/m/.unknown-horizons/save/testmap__.sqlite
Traceback (most recent call last):
  File "/home/m/uh/horizons/main.py", line 335, in start_singleplayer
    _modules.session.load(options)
  File "/home/m/uh/horizons/spsession.py", line 43, in load
    super(SPSession, self).load(*args, **kwargs)
  File "/home/m/uh/horizons/session.py", line 229, in load
    self.view.resize_layers(savegame_db)
  File "/home/m/uh/horizons/view.py", line 252, in resize_layers
    min_x, min_y, max_x, max_y = db("SELECT min(x), min(y), max(x), max(y) FROM ground")[0]
  File "/home/m/uh/horizons/util/dbreader.py", line 48, in __call__
    self.cur.execute(command, args)
OperationalError: no such table: ground
```

After that, the deleted map file (e.g. `maps/test.sqlite`) got recreated. It contains zero bytes. (I opened it with a hex editor.)

I am using Debian (testing). This happens with the current master (Github) as well as with the 2013.3 version. This or a similiar bug has been reported also in #1723 (now closed).

**Comment by ChrisOelmueller** [comment]
Also see #1552 (Automatically distribute multiplayer maps and savegames to players if necessary)

**Comment by jmdejong** [comment]
Ehm, this isn't fixed. The error handling might be a bit better but you still can't play a save without its map file.

**Comment by baka0815** [comment]
Are there plans to change that?
Wouldn't there also be problems if you modify the map after saving?

Should the map be part of the saved game then?

**Comment by jmdejong** [comment]
I would like to change it and make the map part of the saved game (see #2837). If you then modify the map after saving, your savegame will keep using the old unmodified map.
I don't know what the others think of it.

Actually I would like to refactor a lot more of the savegame structure. Preferably all in one go, to minimize the number of savegame-incompatible versions.
This is probably more something for the long term than for the short term though

**Comment by LinuxDonald** [comment]
That's listen as an good idea.
