### ISSUE TITLE
active_messages list index out of range

### ISSUE THREAD

**Issue by stubb** [unknown-horizons/unknown-horizons#2273]
Originally reported in the forums http://forum.unknown-horizons.org/viewtopic.php?f=29&t=7280
```pytb
Traceback (most recent call last):
  File "C:\Program Files (x86)\Unknown Horizons\python\lib\site-packages\fife\extensions\fife_timer.py", line 125, in updateEvent
    self._callback()
  File "C:\Program Files (x86)\Unknown Horizons\python\lib\site-packages\fife\extensions\pychan\tools.py", line 83, in real_callback
    callback(*args,**kwargs)
  File "C:\Program Files (x86)\Unknown Horizons\python\lib\site-packages\fife\extensions\pychan\events.py", line 164, in delayed_f
    f( event )
  File "C:\Program Files (x86)\Unknown Horizons\python\lib\site-packages\fife\extensions\pychan\events.py", line 327, in captured_f
    tools.applyOnlySuitable(self_ref().callbacks[group_name][event_name],event=event,widget=self_ref().widget_ref())
  File "C:\Program Files (x86)\Unknown Horizons\python\lib\site-packages\fife\extensions\pychan\tools.py", line 60, in applyOnlySuitable
    return func(*args,**kwargs)
  File "C:\Program Files (x86)\Unknown Horizons\horizons\util\python\callback.py", line 47, in __call__
    return self.callback(*self.args, **self.kwargs)
  File "C:\Program Files (x86)\Unknown Horizons\horizons\gui\widgets\messagewidget.py", line 208, in show_text
    text = self.active_messages[self.item + index].message
IndexError: list index out of range


Unknown Horizons has crashed.

We are very sorry for this and want to fix the underlying error.
In order to do this, we need the information from the logfile:
C:\Users\admin\Documents\My Games\unknown-horizons\log\unknown-horizons-2014-03-16_16-26-33.log
Please give it to us via IRC or our forum, for both see http://unknown-horizons.org .
n_info(major=2, minor=7, micro=5, releaselevel='final', serial=0)
Platform: Windows-7-6.1.7601-SP1
Using fife version 0.3.unknown, at least 0.3.4 required
Entities: loading grounds
Loading tile_sets...
Done!

```

**Comment by squiddy** [comment]
GUI test to reproduce the issue, you should revert ece8334e02dc760bb73734208ad46d00f0965a65 first though: 

```python
from tests.gui import gui_test

@gui_test(use_dev_map=True, timeout=6000)
def test_foo(gui):
	message_widget = gui.session.ingame_gui.message_widget

	message_widget.add_custom(u'Foobar')
	gui.run()
	message_widget.add_custom(u'Barbaz')
	gui.run()
	message_widget.remove(u'Barbaz')
	gui.run()

	gui.debug()
```

This will create 3 messages. Once you see them all, hover over the third (bottom) message and the game will crash.

**So what's the issue?**

When the messagewidget is drawn, each message is assigned a callback with its current index: https://github.com/unknown-horizons/unknown-horizons/blob/65dfcddc8a529f443ad972f19524bb4879010cec/horizons/gui/widgets/messagewidget.py#L174

```python
   button.name + "/mouseEntered": Callback(self.show_text, index)
```

A IndexError would occur if we somehow manage to delete a message out of order, invalidating the callbacks of messages added earlier. Say `[x]` denotes the message at position `x` in `active_messages` with its callback:

```
[0] self.show_text(0)
[1] self.show_text(1)
[2] self.show_text(2)
```

If we remove the message 0, we end up with:

```
[0] self.show_text(1)
[1] self.show_text(2)
```

Hover over the second message and the access fails. So I looked for ways to remove messages out of order, `MessageWidget.remove` does just that. Which is just by the logbook: https://github.com/unknown-horizons/unknown-horizons/blob/65dfcddc8a529f443ad972f19524bb4879010cec/horizons/gui/widgets/logbook.py#L301

Intuitively i'd suggest changing the access from index-based to id-based, possibly by using an OrderedDict in combination with message ids.
