### ISSUE TITLE
Error when launching unknown-horizons

### ISSUE THREAD

**Issue by pingax** [unknown-horizons/unknown-horizons#2295]
Hi,
I've package uh for Frugalware. Before adding it to our source tree, I wanted to test it. However, Uh doesn't launch. You'll see below the log file generated. FYCI, I use lastest versions of fifengine and fifechan. 

``` pytb
Atlas generation failed. Continuing without atlas support.
This just means that the game will run a bit slower.
It will still run fine unless there are other problems.


Unknown Horizons est tombé en panne.

Nous sommes désolé de cette erreur, nous allons faire notre possible afin de la corriger.
Pour cela, nous avons besoin des informations provenant du journal :
/home/anthony/.unknown-horizons/log/unknown-horizons-2014-08-30_02-15-39.log
Veuillez nous tenir informés via IRC ou via notre forum que vous trouverez sur http://unknown-horizons.org.
7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/lib/python2.7/site-packages', '/usr/lib/python2.7/site-packages/Numeric', '/usr/lib/python2.7/site-packages/PIL', '/usr/lib/python2.7/site-packages/gst-0.10', '/usr/lib/python2.7/site-packages/gtk-2.0', '/usr/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg-info', '/usr/lib/python2.7/site-packages/wx-3.0-gtk2']
PATHSEP: ":" SEP: "/"
LD_LIBRARY_PATH: <undefined>
PATH: /usr/local/bin:/usr/bin:/bin:/usr/lib/jvm/java-7-openjdk/jre/bin:/home/anthony/.rvm/bin
PYTHONPATH <undefined>
Python version: sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0)
Platform: Linux-3.14-fw5-x86_64-with-glibc2.2.5
Using fife version 0.3.unknown, at least 0.3.4 required
Traceback (most recent call last):
  File "/usr/bin/unknown-horizons", line 380, in <module>
    main()
  File "/usr/bin/unknown-horizons", line 189, in main
    ret = horizons.main.start(options)
  File "/usr/lib/python2.7/site-packages/horizons/main.py", line 151, in start
    horizons.globals.fife.init()
  File "/usr/lib/python2.7/site-packages/horizons/engine/engine.py", line 178, in init
    self._setting.apply()
  File "/usr/lib/python2.7/site-packages/horizons/engine/settings.py", line 91, in apply
    change_language(language)
  File "/usr/lib/python2.7/site-packages/horizons/i18n/__init__.py", line 125, in change_language
    horizons.globals.fife.pychan.loadFonts(fontdef)
  File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/fonts.py", line 88, in loadFonts
    for font in Font.loadFromFile(filename):
  File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/fonts.py", line 73, in loadFromFile
    fonts.append( Font(name,_get) )
  File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/fonts.py", line 46, in __init__
    self.font.setAntiAlias(self.antialias)
  File "/usr/lib/python2.7/site-packages/fife/fife.py", line 3233, in setAntiAlias
    return _fife.GuiFont_setAntiAlias(self, *args)
TypeError: in method 'GuiFont_setAntiAlias', argument 2 of type 'bool'
```

Regards, 

Pingax

**Comment by akien-mga** [comment]
I just wanted to ask whether UH 2014.1 was compatible with fife master? I just packaged the latter and UH 2014.1 starts fine, but I can't start a map:
```RuntimeError: _[NotFound]_ , Something was searched, but not found :: content/gfx/units/ships/merchants/as_huker0/color_idle/0/0.png```

**Comment by stubb** [comment]
Yep it is. You need to enable atlas support in your settings.xml so it uses the atlas files and not single png files.

**Comment by ChrisOelmueller** [comment]
Alternatively, apply this patch to the 2014.1 sources: http://git.io/s8Ml4Q

**Comment by akien-mga** [comment]
Thanks @stubb and @ChrisOelmueller. I used the above patch and it works great, I'll go with fife master for Mageia's upcoming stable release then.

**Comment by malkavi** [comment]
I have the same error in OpenSuse 13.2 x64. I'm using the package from the repo, wich have the patch from @ChrisOelmueller . And atlas support is enabled in settings.xml.

**Comment by stubb** [comment]
What do you mean by same error? The one from the first post?

**Comment by malkavi** [comment]
Yes, there is the output:
```
malkavi@linux-a4ba:~> unknown-horizons 
Traceback (most recent call last):
  File "/usr/bin/unknown-horizons", line 380, in <module>
    main()
  File "/usr/bin/unknown-horizons", line 189, in main
    ret = horizons.main.start(options)
  File "/usr/lib/python2.7/site-packages/horizons/main.py", line 192, in start
    horizons.globals.fife.init()
  File "/usr/lib/python2.7/site-packages/horizons/engine/engine.py", line 178, in init
    self._setting.apply()
  File "/usr/lib/python2.7/site-packages/horizons/engine/settings.py", line 91, in apply
    change_language(language)
  File "/usr/lib/python2.7/site-packages/horizons/i18n/__init__.py", line 125, in change_language
    horizons.globals.fife.pychan.loadFonts(fontdef)
  File "/usr/lib64/python2.7/site-packages/fife/extensions/pychan/fonts.py", line 88, in loadFonts
    for font in Font.loadFromFile(filename):
  File "/usr/lib64/python2.7/site-packages/fife/extensions/pychan/fonts.py", line 73, in loadFromFile
    fonts.append( Font(name,_get) )
  File "/usr/lib64/python2.7/site-packages/fife/extensions/pychan/fonts.py", line 46, in __init__
    self.font.setAntiAlias(self.antialias)
  File "/usr/lib64/python2.7/site-packages/fife/fife.py", line 3233, in setAntiAlias
    return _fife.GuiFont_setAntiAlias(self, *args)
TypeError: in method 'GuiFont_setAntiAlias', argument 2 of type 'bool'
AL lib: (EE) alc_cleanup: 1 device not closed
Violación de segmento
```

**Comment by stubb** [comment]
@malkavi Sounds like the fife version is build with swig3.x instead of swig2.x. Now its necessary to inform the maintainer of the package about the problem!

**Comment by malkavi** [comment]
The spec file from the build system has the build requeriment for fife
"BuildRequires:  swig < 3.0.0"
And a comment with a link to this issue in the last change.

**Comment by stubb** [comment]
I saw that. But OBS also says the build failed. So maybe this change wasnt applied correctly?

**Comment by malkavi** [comment]
Thanks! now I can launch the game (still have to try playing). There wasn't any swig package <3.0.0 for Opensuse 13.2, I have branched the Unknown Horizons packages to my build home and a swig package version 2.0.X.
