### ISSUE TITLE
Error. Failed to save / OperationalError: unable to open database file

### ISSUE THREAD

**Issue by stubb** [unknown-horizons/unknown-horizons#2300]
Reported by bcos within #uh.
System is Win 8.1 with release 2013.3
`horizons/util/dbreader.py` crashes at line 48 whenever I try to save a game
with the error `OperationalError: unable to open database file`
on file `C:\Users\bcos\Documents\My Games\unknown-horizons\save\ee.sqlite`
```pytb
INSERT INTO unit (rowid, type, x, y, owner) VALUES(?, ?, ?, ?, ?);
(1045, 1000013, 4, 40, 1001)
INSERT INTO collector(rowid, state, remaining_ticks, start_hidden) VALUES(?, ?, ?, ?);
(1045, 2, 70, False)
INSERT INTO collector_job(collector, object, resource, amount) VALUES(?, ?, ?, ?);
(1045, 1026, 12, 1)
INSERT INTO wildanimal(rowid, health, can_reproduce) VALUES(?, ?, ?);
(1045, 50, 1)
UPDATE unit SET owner = ? WHERE rowid = ?;
(1001, 1045)
Save Exception
Traceback (most recent call last):
  File "D:\UnknownHorizons\horizons\session.py", line 421, in _do_save
    self.world.save(db)
  File "D:\UnknownHorizons\horizons\world\__init__.py", line 663, in save
    island.save(db)
  File "D:\UnknownHorizons\horizons\world\island.py", line 172, in save
    animal.save(db)
  File "D:\UnknownHorizons\horizons\world\units\animal.py", line 147, in save
    db("UPDATE unit SET owner = ? WHERE rowid = ?", self.home_island.worldid, self.worldid)
  File "D:\UnknownHorizons\horizons\util\dbreader.py", line 50, in __call__
    self.cur.execute(command, args)
OperationalError: unable to open database file
```

**Comment by LinuxDonald** [comment]
You can reopen it when anyone will report that problem again.
