### ISSUE TITLE
Crash click at a ship

### ISSUE THREAD

**Issue by MarkusHackspacher** [unknown-horizons/unknown-horizons#2316]
uh crash, if i click at a ship
```pytb
$ ./run_uh.py
Discovered old savegame file, auto-upgrading: 74 -> 74
Traceback (most recent call last):
 File "/home/mar/workspace/python/src/unknown-horizons/horizons/gui/mousetools/selectiontool.py", line 131, in mouseReleased
    self.apply_select()
 File "/home/mar/workspace/python/src/unknown-horizons/horizons/gui/mousetools/selectiontool.py", line 153, in apply_select
    iter(selected).next().get_component(SelectableComponent).show_menu()
 File "/home/mar/workspace/python/src/unknown-horizons/horizons/component/selectablecomponent.py", line 101, in show_menu
    self.session.ingame_gui.show_menu(tabwidget)
 File "/home/mar/workspace/python/src/unknown-horizons/horizons/gui/ingamegui.py", line 304, in show_menu
    self._old_menu.show()
 File "/home/mar/workspace/python/src/unknown-horizons/horizons/gui/tabs/tabwidget.py", line 148, in show
    self._draw_widget()
 File "/home/mar/workspace/python/src/unknown-horizons/horizons/gui/tabs/tabwidget.py", line 140, in _draw_widget
    self.current_tab.refresh()
 File "/home/mar/workspace/python/src/unknown-horizons/horizons/gui/tabs/shiptabs.py", line 137, in refresh
    self.widget.mapEvents(events)
 File "/usr/local/lib/python2.7/dist-packages/fife/extensions/pychan/widgets/widget.py", line 644, in mapEvents
    raise RuntimeError("No widget with the name: %s" % name)
RuntimeError: No widget with the name: discard_res

Traceback (most recent call last):
  File "./run_uh.py", line 407, in <module>
    main()
  File "./run_uh.py", line 197, in main
    ret = horizons.main.start(options)
  File "/home/mar/workspace/python/src/unknown-horizons/horizons/main.py", line 289, in start
    horizons.globals.fife.run()
  File "/home/mar/workspace/python/src/unknown-horizons/horizons/engine/engine.py", line 279, in run
    self.loop()
  File "/home/mar/workspace/python/src/unknown-horizons/horizons/engine/engine.py", line 286, in loop
    self.engine.pump()
  File "/usr/local/lib/python2.7/dist-packages/fife/fife.py", line 2208, in pump
    return _fife.Engine_pump(self)
RuntimeError: Caught a director exception
AL lib: ReleaseALC: 1 device not closed
```

**Comment by ChrisOelmueller** [comment]
As far as I can tell, introduced with `2014.1-29-gd0886fc` (d0886fc1be2fc87a7992ac4a35a5af972b1c0a4f)

@stubb - should all ships receive this button?

**Comment by MarkusHackspacher** [comment]
It is only one ship in this [save game](https://github.com/MarkusHackspacher/unknown-horizons/tree/master/Issues2316), it is at the upper right. 
![Screenshot](https://github.com/MarkusHackspacher/unknown-horizons/blob/master/Issues2316/uh_crach_ship.jpeg?raw=true)
I use the newest version from github, but the fife is a half year old.
