### ISSUE TITLE
Could not find a maching screen mode for the values given!

### ISSUE THREAD

**Issue by daithi-coombes** [unknown-horizons/unknown-horizons#2322]
Came across this error when I switched screen sizes from my latop native screen to my external monitor. Unkown Horizons was initially installed on the laptop screen.

Error:

``` pytb
Controller:LOG:Querying device capabilities
Traceback (most recent call last):
  File "/usr/games/unknown-horizons", line 473, in <module>
    main()
  File "/usr/games/unknown-horizons", line 283, in main
    ret = horizons.main.start(options)
  File "/usr/lib/python2.7/dist-packages/horizons/main.py", line 179, in start
    horizons.globals.fife.init()
  File "/usr/lib/python2.7/dist-packages/horizons/engine/engine.py", line 133, in init
    self.engine.init()
  File "/usr/lib/python2.7/dist-packages/fife/fife.py", line 2185, in init
    return _fife.Engine_init(self)
RuntimeError: _[NotSupported]_ , This action was not supported :: Could not find a maching screen mode for the values given!
Controller:LOG:Destructing engine
Segmentation fault
```

Output from `xrandr`:

```
$ xrandr
Screen 0: minimum 320 x 200, current 1280 x 1024, maximum 8192 x 8192
LVDS1 connected (normal left inverted right x axis y axis)
   1366x768      60.05 +
   1360x768      59.80    59.96  
   1024x768      60.00  
   800x600       60.32    56.25  
   640x480       59.94  
VGA1 disconnected (normal left inverted right x axis y axis)
HDMI1 connected 1280x1024+0+0 (normal left inverted right x axis y axis) 338mm x 270mm
   1280x1024     60.02 +  75.02* 
   1152x864      75.00  
   1024x768      75.08    60.00  
   800x600       75.00    60.32  
   640x480       75.00    60.00  
   720x400       70.08  
DP1 disconnected (normal left inverted right x axis y axis)
```

So, I had installed on `LVDS1` above and then switched monitor to `HDMI1` which caused the crash. Where would I find the config file to manually reset the screen differences for now (and should this work?), also if I get the time I may see if I can get it to auto check active monitor on error
##

**Comment by stubb** [comment]
Hey, here is the FAQ entry for the settings file https://github.com/unknown-horizons/unknown-horizons/wiki/FAQ#settings. The code which does the monitor handling is part of the engine fife. Soon, hopefully within this year the will move the code from SDL1.3 to SDL2 this will improve also the monitor handling.

**Comment by LinuxDonald** [comment]
@daithi-coombes can you please retest it with fife-git/fifechan-git it have now sdl2 support
