### ISSUE TITLE
Click on Main Square cause a crash

### ISSUE THREAD

**Issue by Elinvention** [unknown-horizons/unknown-horizons#2349]
Unknown Horizons, FIFE engine and FIFEChan compiled from git.

```
Traceback (most recent call last):
 File "/home/elia/Giochi/Unknown Horizons/unknown-horizons/horizons/gui/mousetools/selectiontool.py", line 129, in mouseReleased
    self.apply_select()
 File "/home/elia/Giochi/Unknown Horizons/unknown-horizons/horizons/gui/mousetools/selectiontool.py", line 151, in apply_select
    iter(selected).next().get_component(SelectableComponent).show_menu()
 File "/home/elia/Giochi/Unknown Horizons/unknown-horizons/horizons/component/selectablecomponent.py", line 101, in show_menu
    self.session.ingame_gui.show_menu(tabwidget)
 File "/home/elia/Giochi/Unknown Horizons/unknown-horizons/horizons/gui/ingamegui.py", line 315, in show_menu
    self._old_menu.show()
 File "/home/elia/Giochi/Unknown Horizons/unknown-horizons/horizons/gui/tabs/tabwidget.py", line 146, in show
    self.current_tab.show()
 File "/home/elia/Giochi/Unknown Horizons/unknown-horizons/horizons/gui/tabs/mainsquaretabs.py", line 52, in show
    if not building.has_change_listener(self._schedule_refresh):
 File "/home/elia/Giochi/Unknown Horizons/unknown-horizons/horizons/util/changelistener.py", line 98, in has_change_listener
    return (listener in self.__listeners)
TypeError: argument of type 'NoneType' is not iterable

Traceback (most recent call last):
  File "./run_uh.py", line 380, in <module>
    main()
  File "./run_uh.py", line 189, in main
    ret = horizons.main.start(options)
  File "/home/elia/Giochi/Unknown Horizons/unknown-horizons/horizons/main.py", line 281, in start
    horizons.globals.fife.run()
  File "/home/elia/Giochi/Unknown Horizons/unknown-horizons/horizons/engine/engine.py", line 276, in run
    self.loop()
  File "/home/elia/Giochi/Unknown Horizons/unknown-horizons/horizons/engine/engine.py", line 283, in loop
    self.engine.pump()
  File "/home/elia/Giochi/Unknown Horizons/fifengine/engine/python/fife/fife.py", line 2710, in pump
    return _fife.Engine_pump(self)
RuntimeError: Caught a director exception
AL lib: (EE) alc_cleanup: 1 device not closed
```

UPDATE: This happens if I destroy a turret that expands settlement's range (don't know how to say).

**Comment by LinuxDonald** [comment]
I can reproduce the error. Its an an turrent its an signal fire. @stubb can you please take an look on it?

**Comment by LinuxDonald** [comment]
... Not signal fire I mean the lookout

**Comment by stubb** [comment]
Iam not able to reproduce it. Tested it multiple times.

**Comment by LinuxDonald** [comment]
@stubb have you build an new lookout and than removed it and clicked on the marketplace?

**Comment by stubb** [comment]
Oh, reading the headline would have made that clear. I forgot to click on the mainsquare.
