### ISSUE TITLE
Game Crashes when i click on: Cancel game

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2358]
Here is the log:

```python
Discovered old savegame file, auto-upgrading: 75 -> 76
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/fife/extensions/fife_timer.py", line 125, in updateEvent
    self._callback()
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/tools.py", line 83, in real_callback
    callback(*args,**kwargs)
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/events.py", line 173, in delayed_f
    f( event )
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/events.py", line 351, in captured_f
    tools.applyOnlySuitable(self_ref().callbacks[group_name][event_name],event=event,widget=self_ref().widget_ref())
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/tools.py", line 60, in applyOnlySuitable
    return func(*args,**kwargs)
 File "/home/linuxdonald/unknown-horizons/horizons/gui/modules/pausemenu.py", line 90, in _do_quit
    self._session.quit()
 File "/home/linuxdonald/unknown-horizons/horizons/session.py", line 198, in quit
    self.end()
 File "/home/linuxdonald/unknown-horizons/horizons/session.py", line 178, in end
    self.world.end()
 File "/home/linuxdonald/unknown-horizons/horizons/world/__init__.py", line 117, in end
    island.end()
 File "/home/linuxdonald/unknown-horizons/horizons/world/island.py", line 454, in end
    super(Island, self).end()
 File "/home/linuxdonald/unknown-horizons/horizons/world/buildingowner.py", line 149, in end
    self.buildings[-1].remove()
 File "/home/linuxdonald/unknown-horizons/horizons/world/building/storages.py", line 52, in remove
    super(StorageBuilding, self).remove()
 File "/home/linuxdonald/unknown-horizons/horizons/world/building/buildingresourcehandler.py", line 51, in remove
    super(BuildingResourceHandler, self).remove()
 File "/home/linuxdonald/unknown-horizons/horizons/world/resourcehandler.py", line 90, in remove
    super(ResourceHandler, self).remove()
 File "/home/linuxdonald/unknown-horizons/horizons/world/building/building.py", line 121, in remove
    self.island.remove_building(self)
 File "/home/linuxdonald/unknown-horizons/horizons/world/island.py", line 375, in remove_building
    building.settlement.remove_building(building)
AttributeError: 'NoneType' object has no attribute 'remove_building'

Traceback (most recent call last):
  File "./run_uh.py", line 380, in <module>
    main()
  File "./run_uh.py", line 189, in main
    ret = horizons.main.start(options)
  File "/home/linuxdonald/unknown-horizons/horizons/main.py", line 281, in start
    horizons.globals.fife.run()
  File "/home/linuxdonald/unknown-horizons/horizons/engine/engine.py", line 276, in run
    self.loop()
  File "/home/linuxdonald/unknown-horizons/horizons/engine/engine.py", line 283, in loop
    self.engine.pump()
  File "/usr/lib/python2.7/site-packages/fife/fife.py", line 2242, in pump
    return _fife.Engine_pump(self)
RuntimeError: Caught a director exception
AL lib: (EE) alc_cleanup: 1 device not
```

[first.sqlite.zip](https://github.com/unknown-horizons/unknown-horizons/files/149468/first.sqlite.zip)

**Comment by LinuxDonald** [comment]
[1autosave.sqlite.zip](https://github.com/unknown-horizons/unknown-horizons/files/149450/1autosave.sqlite.zip)
Here is another savegame file from an Windows User.
