### ISSUE TITLE
AttributeError with git versions

### ISSUE THREAD

**Issue by konstin** [unknown-horizons/unknown-horizons#2442]
I've followed http://www.unknown-horizons.org/download/sources/s-linux/, and here's what I get for the last step:

```
$ ./setup.py build_i18n && ./run_uh.py
running build_i18n
intltool-merge -d po/uh/ content/packages/unknown-horizons.desktop.in build/share/applications/unknown-horizons.desktop
Merging translations into build/share/applications/unknown-horizons.desktop.
Traceback (most recent call last):
  File "./run_uh.py", line 380, in <module>
    main()
  File "./run_uh.py", line 185, in main
    import horizons.main
  File "/home/konsti/unknown-horizons/horizons/main.py", line 45, in <module>
    from horizons.gui import Gui
  File "/home/konsti/unknown-horizons/horizons/gui/__init__.py", line 22, in <module>
    from gui import Gui
  File "/home/konsti/unknown-horizons/horizons/gui/gui.py", line 36, in <module>
    from horizons.gui.modules.editorstartmenu import EditorStartMenu
  File "/home/konsti/unknown-horizons/horizons/gui/modules/__init__.py", line 26, in <module>
    from singleplayermenu import SingleplayerMenu
  File "/home/konsti/unknown-horizons/horizons/gui/modules/singleplayermenu.py", line 34, in <module>
    from horizons.world import load_raw_world  # FIXME placing this import at the end results in a cycle
  File "/home/konsti/unknown-horizons/horizons/world/__init__.py", line 31, in <module>
    from horizons.world.island import Island
  File "/home/konsti/unknown-horizons/horizons/world/island.py", line 34, in <module>
    from horizons.world.settlement import Settlement
  File "/home/konsti/unknown-horizons/horizons/world/settlement.py", line 37, in <module>
    from horizons.world.resourcehandler import ResourceHandler
  File "/home/konsti/unknown-horizons/horizons/world/resourcehandler.py", line 24, in <module>
    from horizons.gui.tabs import ProductionOverviewTab, InventoryTab
  File "/home/konsti/unknown-horizons/horizons/gui/tabs/__init__.py", line 33, in <module>
    from shiptabs import ShipOverviewTab, FightingShipOverviewTab, \
  File "/home/konsti/unknown-horizons/horizons/gui/tabs/shiptabs.py", line 29, in <module>
    from horizons.gui.widgets.routeconfig import RouteConfig
  File "/home/konsti/unknown-horizons/horizons/gui/widgets/routeconfig.py", line 32, in <module>
    from horizons.gui.widgets.minimap import Minimap
  File "/home/konsti/unknown-horizons/horizons/gui/widgets/minimap.py", line 38, in <module>
    class Minimap(object):
  File "/home/konsti/unknown-horizons/horizons/gui/widgets/minimap.py", line 82, in Minimap
    _dummy_fife_point = fife.Point(0, 0) # use when you quickly need a temporary point
  File "/usr/lib/python2.7/dist-packages/fife/fife.py", line 5639, in __init__
    self.this.append(this)
  File "/usr/lib/python2.7/dist-packages/fife/fife.py", line 5619, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Point, name)
  File "/usr/lib/python2.7/dist-packages/fife/fife.py", line 74, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "/usr/lib/python2.7/dist-packages/fife/fife.py", line 69, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'
```

**Comment by jorgesumle** [comment]
I've installed it on Trisquel today (an Ubuntu-based distribution) and worked fine. Maybe this video helps you: https://goblinrefuge.com/mediagoblin/u/freakspot/m/instalacion-de-unknown-horizons-a-partir-del-codigo-fuente/. Tell us which fifechan and fifengine version are currently installed. `--version ` I think should output that, but I'm not sure. Maybe, you can help with this @LinuxDonald.

**Comment by LinuxDonald** [comment]
I dont know the command for version info. What i can say is that UH Git version only runs with fife git and fifechan git version. And not with the last stable release of fife.

**Comment by MasterofJOKers** [comment]
`python -c 'from fife import fife; print fife.getVersion()'` returns 0.4.0 for me.

On Debian, one could run `dpkg -l | grep -i fife` to see the package version if installed. If you haven't built your own package, that should return nothing. Otherwise, you probably have the old 0.3.5 version from Debian repositories.

**Comment by konstin** [comment]
Here's the output of those commands:
```bash
$ python -c 'from fife import fife; print fife.getVersion()'
0.4.0+39e8b513
$~/unknown-horizons: dpkg -l | grep -i fife
$~/unknown-horizons:
```

**Comment by MasterofJOKers** [comment]
so ... basically, the following does not work for you?
`python -c 'from fife import fife; fife.Point(0, 0)'`

Could you please run `python -c 'from fife import fife; print fife._newclass'` and tell me, if it prints `1` or `0`?

**Comment by MasterofJOKers** [comment]
Could you please open "/usr/lib/python2.7/dist-packages/fife/fife.py" and tell me, whats in line 5640 and 5641? The file generated for me should not be able to exhibit the same behaviour as yours. What version of swig did you use? (`dpkg -l | grep -i swig`)

**Comment by konstin** [comment]
```bash
$ python -c 'from fife import fife; fife.Point(0, 0)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/fife/fife.py", line 5639, in __init__
    self.this.append(this)
  File "/usr/lib/python2.7/dist-packages/fife/fife.py", line 5619, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Point, name)
  File "/usr/lib/python2.7/dist-packages/fife/fife.py", line 74, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "/usr/lib/python2.7/dist-packages/fife/fife.py", line 69, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'
$ python -c 'from fife import fife; print fife._newclass'
1
$ dpkg -l | grep -i swig
ii  swig                                          3.0.8-0ubuntu3                                              amd64        Generate scripting interfaces to C/C++ code
ii  swig3.0                                       3.0.8-0ubuntu3                                              amd64        Generate scripting interfaces to C/C++ code
```

Lines 5640 - 5641 for `/usr/lib/python2.7/dist-packages/fife/fife.py`:
```python
        except Exception:
            self.this = this
```

**Comment by MasterofJOKers** [comment]
This makes no sense to me. Your `AttributeError` should be catched by that `except` right there:
```python
>>> object.__getattr__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'object' has no attribute '__getattr__'
>>> try:
...  object.__getattr__()
... except Exception:
...  print "shiny"
... 
shiny
>>> try:
...  object.__getattr__()
... except BaseException:
...  print "shiny"
... 
shiny
```

On the other hand, if I change my line (which is just `except:`) to yours, I get the same error.  `except BaseException:` works, too. You should probably re-build fife with the `swig2.0` package installed instead of `swig3.0`.

**Comment by MasterofJOKers** [comment]
So it seems to be partly fife's fault for having an own `Exception` class. https://github.com/swig/swig/pull/584 fixes this, which is in swig 3.0.9.

**Comment by konstin** [comment]
I've manually installig swig 3.0.10. The game now finally works. Though I'm not really satisfied with this solution as you normally don't want to build 4 projects from source just to play a game.

**Comment by MasterofJOKers** [comment]
Totally understandable. We are working on a new release and on nightly builds.

**Comment by squiddy** [comment]
I think we can close this one. Looks like an issue with swig 3.0.8 specifically: https://github.com/swig/swig/issues/583
