### ISSUE TITLE
Rare crash when exiting game after placing buildings

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2500]
**Steps**

Unfortunately I don't know yet. I think I placed a couple buildings, perhaps I was still in building mode when I pressed ESC and tried to exit the game.

**Error**
```
Traceback (most recent call last):
 File "/usr/lib/python2.7/site-packages/fife/extensions/fife_timer.py", line 125, in updateEvent
    self._callback()
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/tools.py", line 83, in real_callback
    callback(*args,**kwargs)
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/events.py", line 173, in delayed_f
    f( event )
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/events.py", line 351, in captured_f
    tools.applyOnlySuitable(self_ref().callbacks[group_name][event_name],event=event,widget=self_ref().widget_ref())
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/tools.py", line 60, in applyOnlySuitable
    return func(*args,**kwargs)
 File "/home/unknown-horizons/horizons/gui/modules/pausemenu.py", line 90, in _do_quit
    self._session.quit()
 File "/home/unknown-horizons/horizons/session.py", line 198, in quit
    self.end()
 File "/home/unknown-horizons/horizons/session.py", line 174, in end
    self.ingame_gui = None # keep this before world
 File "/home/unknown-horizons/horizons/util/living.py", line 63, in __set__
    self.__value.end()
 File "/home/unknown-horizons/horizons/gui/ingamegui.py", line 195, in end
    self.cursor.remove()
 File "/home/unknown-horizons/horizons/gui/mousetools/buildingtool.py", line 195, in remove
    self.session.ingame_gui.resource_overview.close_construction_mode()
AttributeError: 'NoneType' object has no attribute 'close_construction_mode'

```

**Comment by squiddy** [comment]
Looking at `IngameGui.end`, the resource overview is set to None before calling `cursor.remove`, which will trigger this error.

The question remains, how does one manage to have the buildingtool active while exiting the game?
