### ISSUE TITLE
Atlas Support is broken on Windows

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2596]
Changes in constans.py:
IS_DEV_VERSION = False
RELEASE_VERSION = u'2017.1'

```
Discovered old settings file, auto-upgrading: 1 -> 38

13, releaselevel='final', serial=0)
Platform: Windows-10-10.0.14393
SYS.PATH: ['C:\\unknown-horizons\\unknown-horizons', 'c:\\unknown-horizons\\python\\python27.zip', 'c:\\unknown-horizons\\python\\DLLs', 'c:\\unknown-horizons\\python\\lib', 'c:\\unknown-horizons\\python\\lib\\plat-win', 'c:\\unknown-horizons\\python\\lib\\lib-tk', 'c:\\unknown-horizons\\python', 'c:\\unknown-horizons\\python\\lib\\site-packages']
PATHSEP: ";" SEP: "\"
LD_LIBRARY_PATH: <undefined>
PATH: C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\GtkSharp\2.12\bin;;c:\unknown-horizons\python;c:\unknown-horizons\python\Lib\site-packages\fife
PYTHONPATH <undefined>
Python version: sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0)
Platform: Windows-10-10.0.14393
Using fife version 0.4.0, at least 0.4.0 required
Traceback (most recent call last):
  File "C:\unknown-horizons\unknown-horizons\run_uh.py", line 379, in <module>
    main()
  File "C:\unknown-horizons\unknown-horizons\run_uh.py", line 190, in main
    ret = horizons.main.start(options)
  File "C:\unknown-horizons\unknown-horizons\horizons\main.py", line 165, in start
    horizons.globals.db = _create_main_db()
  File "C:\unknown-horizons\unknown-horizons\horizons\main.py", line 542, in _create_main_db
    with open(i, "r") as f:
IOError: [Errno 2] No such file or directory: 'content\\atlas.sql'
```

**Comment by jakoch** [comment]
The zip file doesn't contain `content\atlas.sql`: https://github.com/unknown-horizons/unknown-horizons/blob/master/.gitignore#L28

**Comment by LinuxDonald** [comment]
yeah but on linux it works without any problem. That file will be created at first run with atlas.

**Comment by jakoch** [comment]
Well, then the Linux build process uses a `git clone` / `git checkout` of the repository, right?

**Comment by LinuxDonald** [comment]
We don't have this file in git. Or did I don't see it? When I'm correct ./run_uh.py with Atlas support enabled create the files locally.

**Comment by jakoch** [comment]
Well, that means the files are generated on the first run and the `.gitignore` prevents a check-in/upload to the repository. It also indicates that packaging was/is done locally and not automatically from Travis/Appveyor. We could adjust some things here to get automatic releases/deployments for UH.

**Comment by LinuxDonald** [comment]
I think the problem is not that the files are not there. It's more why it works on Linux but not on Windows? Why it don't get created at first start too on Windows?

**Comment by LinuxDonald** [comment]
Error from appveyor:
```
cd "%APPVEYOR_BUILD_FOLDER%\extracted\unknown-horizons"
python horizons\engine\generate_atlases.py 1024
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
Recreating all atlases
Traceback (most recent call last):
  File "horizons\engine\generate_atlases.py", line 431, in <module>
    generator.recreate()
  File "horizons\engine\generate_atlases.py", line 272, in recreate
    self.save()
  File "horizons\engine\generate_atlases.py", line 230, in save
    self._save_metadata()
  File "horizons\engine\generate_atlases.py", line 344, in _save_metadata
    with open(PATHS.ATLAS_METADATA_PATH, 'wb') as file:
IOError: [Errno 2] No such file or directory: u'C:\\Users\\appveyor\\Documents\\My Games\\unknown-horizons\\atlas-metadata.cache'
```

**Comment by LinuxDonald** [comment]
fixed in git.
