### ISSUE TITLE
Atlas Support need to fixed up for fife master version

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2605]
XML merge on fife broke our Atlas loader:

```
[linuxdonald@linuxdonald-pc unknown-horizons]$ ./run_uh.py
Discovered old settings file, auto-upgrading: 1 -> 38
Recreating all atlases
libGL: pci id for fd 9: 1002:67b0, driver radeonsi
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/tls/radeonsi_dri.so
libGL: OpenDriver: trying /usr/lib/xorg/modules/dri/radeonsi_dri.so
libGL: Using DRI3 for screen 0
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Failed to load /home/linuxdonald/.unknown-horizons/save/autosave/autosave-2017-01-13--18-13-17.sqlite
Traceback (most recent call last):
  File "/home/linuxdonald/dev/unknown-horizons/horizons/main.py", line 342, in start_singleplayer
    _modules.session.load(options)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/spsession.py", line 45, in load
    super(SPSession, self).load(*args, **kwargs)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/session.py", line 251, in load
    self.world._init(savegame_db, options.force_player_id, disasters_enabled=options.disasters_enabled)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/world/__init__.py", line 167, in _init
    self.load_raw_map(savegame_db)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/world/__init__.py", line 268, in load_raw_map
    island = Island(savegame_db, islandid, self.session, preview=preview)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/world/island.py", line 97, in __init__
    settlement = Settlement.load(db, settlement_id, self.session, self)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/world/settlement.py", line 188, in load
    building = load_building(session, db, building_type, building_id)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/world/__init__.py", line 737, in load_building
    return Entities.buildings[typeid].load(session, db, worldid)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/world/ingametype.py", line 55, in load
    super(cls, self).load(db, worldid)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/world/building/building.py", line 161, in load
    self.__init(remaining_ticks_of_month=remaining_ticks_of_month)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/world/building/building.py", line 97, in __init
    rotation=self.rotation, action_set_id=self._action_set_id, world_id=str(self.worldid))
  File "/home/linuxdonald/dev/unknown-horizons/horizons/world/building/building.py", line 287, in getInstance
    cls._fife_object,
  File "/home/linuxdonald/dev/unknown-horizons/horizons/world/ingametype.py", line 182, in _fife_object
    self._loadObject()
  File "/home/linuxdonald/dev/unknown-horizons/horizons/world/building/__init__.py", line 90, in _loadObject
    cls._do_load(all_action_sets, action_set, action_id)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/world/building/__init__.py", line 113, in _do_load
    anim = horizons.globals.fife.animationloader.loadResource(path)
  File "/home/linuxdonald/dev/unknown-horizons/horizons/util/loaders/sqliteatlasloader.py", line 75, in loadResource
    ani = fife.Animation.createAnimation()
AttributeError: type object 'Animation' has no attribute 'createAnimation'
function is no-op
function is no-op
```

Helios sad that line: https://github.com/unknown-horizons/unknown-horizons/blob/master/horizons/util/loaders/sqliteanimationloader.py#L56
must be changed to: ani = fife.AnimationManager().getPtr(str(id))
but this gives new error:

```
  File "/home/linuxdonald/dev/unknown-horizons/horizons/util/loaders/sqliteatlasloader.py", line 75, in loadResource
    ani = fife.AnimationManager().getPtr(str(id))
AttributeError: 'AnimationManager' object has no attribute 'getPtr'
```

Maybe that helps: https://github.com/fifengine/fifengine/blob/master/engine/python/fife/extensions/serializers/xmlanimation.py

**Comment by LinuxDonald** [comment]
Fixed in master
