### ISSUE TITLE
python3 version bug

### ISSUE THREAD

**Issue by melloskitten** [unknown-horizons/unknown-horizons#2646]
Whenever I try to run the master branch, I get this error: (I'm using Python 3.4.3)
(Using the ```python3 ./setup.py build_i18n``` command)

```python3 ./setup.py build_i18n
Traceback (most recent call last):
  File "./setup.py", line 33, in <module>
    from horizons.constants import VERSION
  File "/usr/local/General/Code_Projects/uh/unknown-horizons/horizons/constants.py", line 29, in <module>
    from typing import Optional
ImportError: No module named 'typing' 
```

Do I also have to update fife & fifengine, etc to make it work...?

**Comment by LinuxDonald** [comment]
Yes you need lastest fife git version. We changed to python3. And you need to rebuild.

**Comment by melloskitten** [comment]
So not the latest release but the master branch?

**Comment by melloskitten** [comment]
Ah alright then. Just one little question, because when I build fife, it always finds the python2.7 libs - do you know how i can manually choose py3 libs?

**Comment by Beliaar** [comment]
you need to set the PYTHON_EXECUTABLE cmake option to the path of python3.

From command like this would be like
"cmake -DPYTHON_EXECUTABLE=<path to the python binary>"

**Comment by melloskitten** [comment]
I'm sorry if I'm doing this wrong (I'm a noob), but when I try to run:
```
cmake -DPYTHON_EXECUTABLE=PATH=/usr/bin/python3 -DCMAKE_INSTALL_PREFIX:PATH=/usr -D CMAKE_C_COMPILER=clang-3.9 -D CMAKE_CXX_COMPILER=clang++-3.9 ..

```

and this is the output I get -> 
```
== Updating version.h with version information and git meta data.

== Building FIFE version 0.4.1+build.ca5ef7a using build type 'Release'.
--     Source directory is '/home/sandra/fifengine'.
--     Build  directory is '/home/sandra/fifengine/_build'.
--     Installation path is '/usr' (set -DCMAKE_INSTALL_PREFIX=<path> to change).
--     Dependencies folder: '/home/sandra/fifengine/../fifengine-dependencies'.

--     CMake version is '3.2.2'.
--     CXX Compiler ID: 'Clang'.
--     CXX Compiler Flags: '-std=c++11 -fPIC  -O2 -Wno-error'.

-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   filesystem
-- Found PythonInterp: /home/sandra/fifengine/_build/PATH=/usr/bin/python3 (found version "1.4") 
-- Found the following FifeChan libraries:
--   fifechan_sdl
-- Found the following FifeChan libraries:
--   fifechan_opengl
-- Could NOT find PythonLibs: Found unsuitable version "2.7.6", but required is exact version "1.4" (found PYTHON_LIBRARY-NOTFOUND)
CMake Error at CMakeLists.txt:962 (file):
  file FILE([TO_CMAKE_PATH|TO_NATIVE_PATH] path result) must be called with
  exactly three arguments.


--     Python install directory is '/fife'.
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PYTHON_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/sandra/fifengine
   used as include directory in directory /home/sandra/fifengine
   used as include directory in directory /home/sandra/fifengine
   used as include directory in directory /home/sandra/fifengine
PYTHON_LIBRARY (ADVANCED)
    linked by target "_fifechan" in directory /home/sandra/fifengine
    linked by target "_fife" in directory /home/sandra/fifengine

-- Configuring incomplete, errors occurred!
See also "/home/sandra/fifengine/_build/CMakeFiles/CMakeOutput.log".
See also "/home/sandra/fifengine/_build/CMakeFiles/CMakeError.log".
```

Thank you very much for the quick replies!

**Comment by LinuxDonald** [comment]
What linux distro do you have?

No spaces between -D and CMAKEXXXXX
`cmake -DPYTHON_EXECUTABLE=PATH=/usr/bin/python3 -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_C_COMPILER=clang-3.9 -DCMAKE_CXX_COMPILER=clang++-3.9 ..`

**Comment by melloskitten** [comment]
Oh sorry I overlooked the space. Same error even with the removed space.

I'm using Linux Mint 17.3 Cinnamon 64-bit, version 2.8.8.

**Comment by LinuxDonald** [comment]
You can join too irc folr help server freenode channel #unknown-horizons

**Comment by melloskitten** [comment]
will do :)
