### ISSUE TITLE
"ValueError: I/O operation on closed file." when exiting UH started with "--debug"

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2681]
**Steps to reproduce**

1. `$ python run_uh.py --debug`
... lots of messages appearing ...
2. Exit the game via the menu
3. Game stops, exception is raised:

```
Thank you for using Unknown Horizons!Traceback (most recent call last):
  File "run_uh.py", line 382, in <module>
    main()
  File "run_uh.py", line 211, in main
    print(T('Thank you for using Unknown Horizons!'))
  File "run_uh.py", line 263, in write
    logfile.write(line)
ValueError: I/O operation on closed file.

Error in sys.excepthook:
Traceback (most recent call last):
  File "run_uh.py", line 120, in excepthook
    print('\n', T('Unknown Horizons has crashed.'), '\n')
  File "run_uh.py", line 263, in write
    logfile.write(line)
ValueError: I/O operation on closed file.

Original exception was:
Traceback (most recent call last):
  File "run_uh.py", line 382, in <module>
    main()
  File "run_uh.py", line 211, in main
    print(T('Thank you for using Unknown Horizons!'))
  File "run_uh.py", line 263, in write
    logfile.write(line)
ValueError: I/O operation on closed file.
Exception ignored in: <__main__.setup_debugging.<locals>.StdOutDuplicator object at 0x7f884bfe4f28>
Traceback (most recent call last):
  File "run_uh.py", line 266, in flush
    logfile.flush()
ValueError: I/O operation on closed file.
```

**Comment by AndyMender** [comment]
Did the debug mode work properly previously? I might have a look at this.

**Comment by squiddy** [comment]
No clue, haven't used it in a while. The logging still works fine though, it's just that there are exception raised when closing the game. Minor issue really.

**Comment by squiddy** [comment]
Going to have a look at it. Log handling in the `run_uh.py` file looks a bit messy.

**Comment by LinuxDonald** [comment]
Thank you for using Unknown Horizons!Traceback (most recent call last):
  File "/home/thomas/Downloads/unknown-horizons/./run_uh.py", line 381, in <module>
    main()
    ~~~~^^
  File "/home/thomas/Downloads/unknown-horizons/./run_uh.py", line 127, in main
    print(T('Thank you for using Unknown Horizons!'))
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/Downloads/unknown-horizons/./run_uh.py", line 255, in write
    logfile.write(line)
    ~~~~~~~~~~~~~^^^^^^
ValueError: I/O operation on closed file.

Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/thomas/Downloads/unknown-horizons/./run_uh.py", line 183, in excepthook
    print('\n', T('Unknown Horizons has crashed.'), '\n')
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/Downloads/unknown-horizons/./run_uh.py", line 255, in write
    logfile.write(line)
    ~~~~~~~~~~~~~^^^^^^
ValueError: I/O operation on closed file.

Original exception was:
Traceback (most recent call last):
  File "/home/thomas/Downloads/unknown-horizons/./run_uh.py", line 381, in <module>
    main()
    ~~~~^^
  File "/home/thomas/Downloads/unknown-horizons/./run_uh.py", line 127, in main
    print(T('Thank you for using Unknown Horizons!'))
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/Downloads/unknown-horizons/./run_uh.py", line 255, in write
    logfile.write(line)
    ~~~~~~~~~~~~~^^^^^^
ValueError: I/O operation on closed file.
Exception ignored while flushing sys.stdout:
Traceback (most recent call last):
  File "/home/thomas/Downloads/unknown-horizons/./run_uh.py", line 258, in flush
    logfile.flush()
ValueError: I/O operation on closed file.
fish: Job 1, './run_uh.py' terminated by signal SIGSEGV (Adressbereichsfehler)

**Comment by jakoch** [comment]
- setup_debugging() replaces sys.stdout with StdOutDuplicator that writes to logfile
  ref. https://github.com/unknown-horizons/unknown-horizons/blob/master/run_uh.py#L211-L259
- After game ends, logfile.close() is called
- sys.stdout is StdOutDuplicator and points to the closed logfile
- print() uses StdOutDuplicator.write() and tries to write to closed logfile = crash
