### ISSUE TITLE
Fix randomly failing tests.gui.test_internal.py::test_run_for_x_seconds

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2711]
The test fails sometimes on Travis CI:

```
____________________________ test_run_for_x_seconds ____________________________
fatal: No names found, cannot describe anything.
Xlib:  extension "RANDR" missing on display ":99.0".
Traceback (most recent call last):
  File "/home/travis/build/unknown-horizons/unknown-horizons/tests/gui/__init__.py", line 127, in _tick
    cooperative.schedule()
  File "/home/travis/build/unknown-horizons/unknown-horizons/tests/gui/cooperative.py", line 86, in schedule
    g.switch(*args, **kwargs)
  File "/home/travis/build/unknown-horizons/unknown-horizons/tests/gui/test_internal.py", line 51, in test_run_for_x_seconds
    assert (difference - expected) / difference < 0.05
AssertionError
```

A first step is to improve the assertion message and have it print out what the actual difference is. Perhaps Travis is a bit slow and we just need to adjust the delta of `0.05`.

**Comment by squiddy** [comment]
Haven't seen that error in a while. I've added a message when the assertion fails, next time it happens we can consider increasing the threshold. Assuming that's where the problem is.

Until then, closing this one.
