### ISSUE TITLE
Current code doesn't work with fifengine HEAD

### ISSUE THREAD

**Issue by vmx** [unknown-horizons/unknown-horizons#2750]
I've tried to run Unknown Horizons from source with a self compiled fifengine/fifechan. I used HEAD from all of them. Due to https://github.com/fifengine/fifengine/pull/1041 UH doesn't really work anymore and also many GUI tests are failing due to:

```
Traceback (most recent call last):
  File "run_uh.py", line 384, in <module>
    main()
  File "run_uh.py", line 127, in main
    ret = horizons.main.start(options)
  File "/home/vmx/src/python/unknown-horizons/unknown-horizons/horizons/main.py", line 207, in start
    startup_worked = edit_map(command_line_arguments.edit_map)
  File "/home/vmx/src/python/unknown-horizons/unknown-horizons/horizons/main.py", line 550, in edit_map
    return _edit_map(_find_map(map_name, SavegameManager.get_maps()))
  File "/home/vmx/src/python/unknown-horizons/unknown-horizons/horizons/main.py", line 539, in _edit_map
    start_singleplayer(options)
  File "/home/vmx/src/python/unknown-horizons/unknown-horizons/horizons/main.py", line 332, in start_singleplayer
    _modules.session = session_class(horizons.globals.db)
  File "/home/vmx/src/python/unknown-horizons/unknown-horizons/horizons/editor/session.py", line 37, in __init__
    super().__init__(*args, **kwargs)
  File "/home/vmx/src/python/unknown-horizons/unknown-horizons/horizons/session.py", line 110, in __init__
    self.view = View()
  File "/home/vmx/src/python/unknown-horizons/unknown-horizons/horizons/view.py", line 76, in __init__
    self.cam = self.map.addCamera("main", self.layers[-1], rect)
TypeError: Map_addCamera() takes at most 3 arguments (4 given)
```

I've tried to fix some errors with things like

```diff
-               loc = self.cam.getLocationRef()
-               pos = loc.getExactLayerCoordinatesRef()
+               pos = self.cam.getPosition()
```

But there were occurrences where I just don't know enough about the code to make the proper changes.

**Comment by LinuxDonald** [comment]
You use outdated UH code please update to last git version.

**Comment by vmx** [comment]
You are right, sorry for the noise.

**Comment by LinuxDonald** [comment]
No problem :-)
