### ISSUE TITLE
crash when selecting multiple objects

### ISSUE THREAD

**Issue by jmdejong** [unknown-horizons/unknown-horizons#2803]
When selecting multiple objects by dragging the mouse the game crashes with the following stacktrace:

    Traceback (most recent call last):
    File "/data/programming/uh/unknown-horizons/horizons/gui/mousetools/selectiontool.py", line 129, in mouseReleased
        self.apply_select()
    File "/data/programming/uh/unknown-horizons/horizons/gui/mousetools/selectiontool.py", line 153, in apply_select
        self.session.ingame_gui.show_multi_select_tab(selected)
    File "/data/programming/uh/unknown-horizons/horizons/gui/ingamegui.py", line 245, in show_multi_select_tab
        tab = TabWidget(self, tabs=[SelectMultiTab(instances)], name='select_multi')
    File "/data/programming/uh/unknown-horizons/horizons/gui/tabs/tabwidget.py", line 53, in __init__
        self.current_tab.ensure_loaded() # loading current_tab widget
    File "/data/programming/uh/unknown-horizons/horizons/gui/tabs/tabinterface.py", line 163, in ensure_loaded
        self._setup_widget()
    File "/data/programming/uh/unknown-horizons/horizons/gui/tabs/tabinterface.py", line 100, in _setup_widget
        self.widget = self.get_widget()
    File "/data/programming/uh/unknown-horizons/horizons/gui/tabs/tabinterface.py", line 110, in get_widget
        return load_uh_widget(self.widget)
    File "/data/programming/uh/unknown-horizons/horizons/gui/util.py", line 86, in load_uh_widget
        widget = loadXML(BytesIO(get_widget_xml(filename)))
    File "/usr/lib/python3.6/site-packages/fife/extensions/pychan/__init__.py", line 424, in loadXML
        parse(filename_or_stream,loader)
    File "/usr/lib/python3.6/xml/sax/__init__.py", line 33, in parse
        parser.parse(source)
    File "/usr/lib/python3.6/xml/sax/expatreader.py", line 111, in parse
        xmlreader.IncrementalParser.parse(self, source)
    File "/usr/lib/python3.6/xml/sax/xmlreader.py", line 125, in parse
        self.feed(buffer)
    File "/usr/lib/python3.6/xml/sax/expatreader.py", line 217, in feed
        self._parser.Parse(data, isFinal)
    File "/build/python/src/Python-3.6.5/Modules/pyexpat.c", line 414, in StartElement
        
    File "/usr/lib/python3.6/xml/sax/expatreader.py", line 333, in start_element
        self._cont_handler.startElement(name, AttributesImpl(attrs))
    File "/usr/lib/python3.6/site-packages/fife/extensions/pychan/__init__.py", line 358, in startElement
        self._createInstance(cls,name,attrs)
    File "/usr/lib/python3.6/site-packages/fife/extensions/pychan/__init__.py", line 364, in _createInstance
        obj = cls(parent=self.root)
    File "/data/programming/uh/unknown-horizons/horizons/gui/widgets/unitoverview.py", line 37, in __init__
        widget = load_uh_widget('stancewidget.xml')
    File "/data/programming/uh/unknown-horizons/horizons/gui/util.py", line 86, in load_uh_widget
        widget = loadXML(BytesIO(get_widget_xml(filename)))
    File "/usr/lib/python3.6/site-packages/fife/extensions/pychan/__init__.py", line 424, in loadXML
        parse(filename_or_stream,loader)
    File "/usr/lib/python3.6/xml/sax/__init__.py", line 33, in parse
        parser.parse(source)
    File "/usr/lib/python3.6/xml/sax/expatreader.py", line 111, in parse
        xmlreader.IncrementalParser.parse(self, source)
    File "/usr/lib/python3.6/xml/sax/xmlreader.py", line 125, in parse
        self.feed(buffer)
    File "/usr/lib/python3.6/xml/sax/expatreader.py", line 217, in feed
        self._parser.Parse(data, isFinal)
    File "/build/python/src/Python-3.6.5/Modules/pyexpat.c", line 414, in StartElement
        
    File "/usr/lib/python3.6/xml/sax/expatreader.py", line 333, in start_element
        self._cont_handler.startElement(name, AttributesImpl(attrs))
    File "/usr/lib/python3.6/site-packages/fife/extensions/pychan/__init__.py", line 355, in startElement
        cls = self._resolveTag(name)
    File "/usr/lib/python3.6/site-packages/fife/extensions/pychan/__init__.py", line 337, in _resolveTag
        raise GuiXMLError("Unknown GUI Element: %s" % name)
    fife.extensions.pychan.exceptions.GuiXMLError: Unknown GUI Element: ToggleImageButton

    Unknown Horizons exited uncleanly via SIGINT
    AL lib: (EE) alc_cleanup: 1 device not closed

By testing in different previous versions I found that this problem was  introduced in this commit: 8b7fd55b8faa44a6cd7b7c2ad81eb5a07546f528
This commit merges PR #2759

It introduces the `ToggleImageButton` element in stancewidget.xml, but `ToggleImageButton` does not exist. It was removed in #2054

EDIT:
Does not only apply to ships; also happens when selecting multiple buildings

**Comment by LinuxDonald** [comment]
Please retest ist :)

**Comment by jmdejong** [comment]
Traceback (most recent call last):
    File "/data/programming/uh/unknown-horizons/horizons/gui/mousetools/selectiontool.py", line 129, in mouseReleased
        self.apply_select()
    File "/data/programming/uh/unknown-horizons/horizons/gui/mousetools/selectiontool.py", line 153, in apply_select
        self.session.ingame_gui.show_multi_select_tab(selected)
    File "/data/programming/uh/unknown-horizons/horizons/gui/ingamegui.py", line 245, in show_multi_select_tab
        tab = TabWidget(self, tabs=[SelectMultiTab(instances)], name='select_multi')
    File "/data/programming/uh/unknown-horizons/horizons/gui/tabs/tabwidget.py", line 53, in __init__
        self.current_tab.ensure_loaded() # loading current_tab widget
    File "/data/programming/uh/unknown-horizons/horizons/gui/tabs/tabinterface.py", line 163, in ensure_loaded
        self._setup_widget()
    File "/data/programming/uh/unknown-horizons/horizons/gui/tabs/tabinterface.py", line 102, in _setup_widget
        self.init_widget()
    File "/data/programming/uh/unknown-horizons/horizons/gui/tabs/selectmultitab.py", line 79, in init_widget
        self.draw_selected_units_widget()
    File "/data/programming/uh/unknown-horizons/horizons/gui/tabs/selectmultitab.py", line 105, in draw_selected_units_widget
        self.add_entry(UnitEntry(instances))
    File "/data/programming/uh/unknown-horizons/horizons/gui/tabs/selectmultitab.py", line 83, in add_entry
        self.hbox = HBox(name="hbox_%s" % self.row_number)
    NameError: name 'HBox' is not defined

    Unknown Horizons exited uncleanly via SIGINT

Still crashes, but differently

**Comment by jmdejong** [comment]
when fixing the import error I get this:

    Traceback (most recent call last):
    File "./run_uh.py", line 381, in <module>
        main()
    File "./run_uh.py", line 123, in main
        ret = horizons.main.start(options)
    File "/data/programming/uh/unknown-horizons/horizons/main.py", line 255, in start
        horizons.globals.fife.run()
    File "/data/programming/uh/unknown-horizons/horizons/engine/engine.py", line 279, in run
        self.loop()
    File "/data/programming/uh/unknown-horizons/horizons/engine/engine.py", line 296, in loop
        f()
    File "/data/programming/uh/unknown-horizons/horizons/extscheduler.py", line 71, in tick
        obj.callback()
    File "/data/programming/uh/unknown-horizons/horizons/gui/widgets/unitoverview.py", line 57, in refresh
        self.toggle_stance()
    File "/data/programming/uh/unknown-horizons/horizons/gui/widgets/unitoverview.py", line 72, in toggle_stance
        self.findChild(name=self.instance.stance.NAME).set_active()
    AttributeError: 'StanceWidget' object has no attribute 'instance'

**Comment by LinuxDonald** [comment]
:( maybe i should revert the pr...
