### ISSUE TITLE
UH Crash with lastest master

### ISSUE THREAD

**Issue by LinuxDonald** [unknown-horizons/unknown-horizons#2819]
```
linuxdonald@linuxdonald-desktop:~/dev/unknown-horizons$ ./run_uh.py
Traceback (most recent call last):
 File "/usr/lib/python3/dist-packages/fife/extensions/fife_timer.py", line 125, in updateEvent
    self._callback()
 File "/usr/lib/python3/dist-packages/fife/extensions/pychan/tools.py", line 94, in real_callback
    callback(*args,**kwargs)
 File "/usr/lib/python3/dist-packages/fife/extensions/pychan/events.py", line 194, in delayed_f
    f( event )
 File "/usr/lib/python3/dist-packages/fife/extensions/pychan/events.py", line 374, in captured_f
    tools.applyOnlySuitable(self_ref().callbacks[group_name][event_name],event=event,widget=self_ref().widget_ref())
 File "/usr/lib/python3/dist-packages/fife/extensions/pychan/tools.py", line 71, in applyOnlySuitable
    return func(*args,**kwargs)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/util/python/callback.py", line 47, in __call__
    return self.callback(*self.args, **self.kwargs)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/modules/singleplayermenu.py", line 102, in _select_mode
    self._mode.show()
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/modules/singleplayermenu.py", line 403, in show
    self._update_map_infos()
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/modules/singleplayermenu.py", line 416, in _update_map_infos
    self._update_map_preview(map_file)
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/modules/singleplayermenu.py", line 442, in _update_map_preview
    self._map_preview.draw()
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/widgets/minimap.py", line 226, in draw
    self.update_rotation()
 File "/home/linuxdonald/dev/unknown-horizons/horizons/gui/widgets/minimap.py", line 625, in update_rotation
    self.transform.set_rotation(self.view.cam.getRotation())
AttributeError: 'NoneType' object has no attribute 'cam'

Unknown Horizons exited uncleanly via SIGINT
AL lib: (EE) alc_cleanup: 1 device not closed

```

**Comment by LinuxDonald** [comment]
@jmdejong could you please take an look?

**Comment by LinuxDonald** [comment]
Starting an new game free to play
