### ISSUE TITLE
Taking screenshot while loading crashes game

### ISSUE THREAD

**Issue by jmdejong** [unknown-horizons/unknown-horizons#2833]
If you press the 'take screenshot' button ('S' by default) while the map is loading, the game crashes.
It then shows the standard message that the save might be corrupted (even when generating a random map) and takes you back to the menu

Edit: Here's the traceback by the way. I started it from command line and kept mashing 'S' while the game was loading:

    $ ./run_uh.py --start-random-map
    Traceback (most recent call last):
    File "/data/programming/uh/unknown-horizons/horizons/gui/keylisteners/mainlistener.py", line 86, in keyPressed
        session.ingame_gui.message_widget.add('SCREENSHOT',
    AttributeError: 'NoneType' object has no attribute 'message_widget'

    Failed to load ['random:2:70:70:949028245:39:23', 'random:2:47:38:18177917:70:98', 'random:2:48:45:-50844443:0:105', 'random:2:23:20:2116520387:127:0', 'random:2:20:20:-785767074:123:37', 'random:2:20:28:-1087316948:8:16', 'random:2:20:20:447274611:127:73', 'random:2:20:20:1153797000:125:108']
    Traceback (most recent call last):
    File "/data/programming/uh/unknown-horizons/horizons/main.py", line 344, in start_singleplayer
        session.load(options)
    File "/data/programming/uh/unknown-horizons/horizons/spsession.py", line 45, in load
        super().load(*args, **kwargs)
    File "/data/programming/uh/unknown-horizons/horizons/session.py", line 255, in load
        self.world._init(savegame_db, options.force_player_id, disasters_enabled=options.disasters_enabled)
    File "/data/programming/uh/unknown-horizons/horizons/world/__init__.py", line 167, in _init
        LoadingProgress.broadcast(self, 'world_load_buildings')
    File "/data/programming/uh/unknown-horizons/horizons/messaging/message.py", line 120, in broadcast
        cls.bus().broadcast(cls(*args))
    File "/data/programming/uh/unknown-horizons/horizons/messaging/messagebus.py", line 75, in broadcast
        callback(message)
    File "/data/programming/uh/unknown-horizons/horizons/gui/modules/loadingscreen.py", line 212, in _update
        horizons.globals.fife.engine.pump()
    RuntimeError: Caught a director exception

**Comment by AndyMender** [comment]
From the traceback it seems the in-game GUI is in the process of being loaded, but the main listener already listens for key-press events. I guess an `is None` check for the GUI could address this.
