### ISSUE TITLE
2019.1: FileNotFoundError content/atlas.sql

### ISSUE THREAD

**Issue by apoleon** [unknown-horizons/unknown-horizons#2892]
Hello,

I intented to upgrade UH from Debian version 2017.2+git20180906, a Git snapshot, to 2019. However when I try to start the game I get this error message:
Traceback (most recent call last):
  File "/usr/games/unknown-horizons", line 381, in <module>
    main()
  File "/usr/games/unknown-horizons", line 122, in main
    ret = horizons.main.start(options)
  File "/usr/lib/python3/dist-packages/horizons/main.py", line 173, in start
    horizons.globals.db = _create_main_db()
  File "/usr/lib/python3/dist-packages/horizons/main.py", line 587, in _create_main_db
    with open(i, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'content/atlas.sql'

I have removed my settings.xml file in ~/.config/unknown-horizons and also deleted ~/.unknown-horizons/

If UH tries to create atlas.sql at startup, then it won't work because the content directory is in /usr/share/ which is read-only. Also the --no-atlas-generation option, documented in the manpage, does not work anymore. (no such option error)

**Comment by MarkusHackspacher** [comment]
That is not a good way, let the Debian paket as they are.
Better make a new dir in your home for ex. games. 
cd games
git clone git@github.com:unknown-horizons/unknown-horizons.git
cd unknown-horizons
./run_uh.py

if you want the newest version you can update with:
git pull git@github.com:unknown-horizons/unknown-horizons.git

**Comment by apoleon** [comment]
I maintain UH for Debian.

**Comment by MarkusHackspacher** [comment]
https://github.com/unknown-horizons/unknown-horizons/wiki/Databases
try to generate 'content/atlas.sql' with development/generate_atlases.py

**Comment by apoleon** [comment]
Maybe I was not clear in my initial report. atlas.sql is not part of your source tarball distribution. It used to work with the Git snapshot from September 2018 even without this database present. I simply upgraded to 2019.1 and I expected no bahavioral change. If users are supposed to generate atlas.sql then it should be documented somehow. It also cannot be installed into the content directory because this one is installed into /usr/share/ on Debian systems and most likely all Linux based distributions. If atlas.sql should be writeable it must be installed into a writable directory like the user's home directory or if it should be system-writable, into /var/lib. Ideally your build system should take care of it.

**Comment by MarkusHackspacher** [comment]
It is the same case like:
https://github.com/unknown-horizons/unknown-horizons/issues/2716

**Comment by LinuxDonald** [comment]
The atlas file was an part of the old sourcetarball for example 2017.x releases. For now setup.py create the atlas files.

**Comment by apoleon** [comment]
I run setup.py build_i18n as documented in https://github.com/unknown-horizons/unknown-horizons/wiki/Linux. The build log says:

The Python Imaging Library (PIL / Pillow) package is needed to run the atlas generator.

Ok, now I have python3-pil installed but then I get the following error message

error: can't copy 'content/gfx/atlas/010.png': doesn't exist or not a regular file

What am I missing?

**Comment by LinuxDonald** [comment]
I dont get the error in my home folder (using ubuntu)

What you could try is comment out Line 148-152: https://github.com/unknown-horizons/unknown-horizons/blob/master/setup.py#L148

And run development/generate_atlases.py from the unknown-horizons folder.

**Comment by LinuxDonald** [comment]
@jmdejong any idea?

**Comment by jmdejong** [comment]
distribute the atlases with the build anyways?

**Comment by apoleon** [comment]
I think building the atlas files from source is a good thing no matter if it is a development or release version. You will also ensure that your tooling works and your data is modifiable which is also more in spirit with your licensing terms.

I found out that my error message appears to be releated to POSIX semaphores.

https://stackoverflow.com/questions/2009278/python-multiprocessing-permission-denied

Apparently I have to remount my chroot environment and make /dev/shm read and writable for my normal user. Using chroot environments is quite common when building Debian packages and I don't know if our autobuilders will be affected by it too. Anyways I patched setup.py for now and commented out line 231

 self.generate_atlases(2048)

I just run the script from debian/rules which is basically a Makefile. Maybe you can find another way to spawn this script. At the moment that works for me.

**Comment by jmdejong** [comment]
Atlas generation can safely be skipped, but the game will run slower.

The easiest way to fix the multiprocessing error is to just remove the multiprocessing entirely. All it does is speed up the install a little bit. It looks like it can safely be done synchronously.

**Comment by theMarix** [comment]
I also ran into this when working on the SUSE package. Weirdly, while the `setup.py`  would generate an atlas, that was actually broken. However, this only showed when starting a game. I would get messages like `Something was searched, but not found :: content/gfx/atlas/054.png` as the `atlas.sql` contained more entries than there actually were images in `content/gfx/atlas`. Weirdly, if I run the generation script manually like it is done in the `create_release_tarball.sh` script, then I get a working atlas and can successfully launch the tutorial.

**Comment by jEsuSdA** [comment]
Same problem here:

```
Traceback (most recent call last):
  File "./run_uh.py", line 381, in <module>
    main()
  File "./run_uh.py", line 122, in main
    ret = horizons.main.start(options)
  File "/mnt/ftp/juegos/install/unknown-horizons/unknown-horizons-2019.1/horizons/main.py", line 173, in start
    horizons.globals.db = _create_main_db()
  File "/mnt/ftp/juegos/install/unknown-horizons/unknown-horizons-2019.1/horizons/main.py", line 587, in _create_main_db
    with open(i, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'content/atlas.sql'

```

**Comment by jEsuSdA** [comment]
I found the solution:

 I launched the __development/create_release_tarball.sh___

and the content into __build__ folder is playable.
;)
