### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by flupke256** [unknown-horizons/unknown-horizons#2905]
Hi,

Here is the log produced : 

```
Arguments: (<horizons.ai.aiplayer.AIPlayer object at 0x07D72B70>, <horizons.ai.aiplayer.goal.donothing.DoNothingGoal object at 0x132C7370>)
--- Logging error ---
Traceback (most recent call last):
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 829, in format    return fmt.format(record)
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 569, in format    record.message = record.getMessage()
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
  File "E:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\goal\__init__.py", line 86, in __str__
    self.priority, self.__class__.__name__, self.sequence_number)
ValueError: Unknown format code 'd' for object of type 'float'
Call stack:
  File "E:\Unknown-Horizons\unknown-horizons\run_uh.py", line 381, in <module>
    main()
  File "E:\Unknown-Horizons\unknown-horizons\run_uh.py", line 122, in main
    ret = horizons.main.start(options)
  File "E:\Unknown-Horizons\unknown-horizons\horizons\main.py", line 255, in start
    horizons.globals.fife.run()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\engine\engine.py", line 279, in run
    self.loop()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\engine\engine.py", line 296, in loop
    f()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\timer.py", line 112, in check_tick
    f(self.tick_next_id)
  File "E:\Unknown-Horizons\unknown-horizons\horizons\scheduler.py", line 95, in tick
    callback.callback()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\util\python\callback.py", line 48, in __call__
    return self.callback(*self.args, **self.kwargs)
  File "E:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\__init__.py", line 317, in tick
    self.handle_settlements()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\__init__.py", line 354, in handle_settlements
    self.log.info('%s all further goals during this tick blocked by goal %s', self, goal)
Message: '%s all further goals during this tick blocked by goal %s'
Arguments: (<horizons.ai.aiplayer.AIPlayer object at 0x07D72B70>, <horizons.ai.aiplayer.goal.donothing.DoNothingGoal object at 0x132C7370>)
--- Logging error ---
Traceback (most recent call last):
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 829, in format    return fmt.format(record)
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 569, in format    record.message = record.getMessage()
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
  File "E:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\goal\__init__.py", line 86, in __str__
    self.priority, self.__class__.__name__, self.sequence_number)
ValueError: Unknown format code 'd' for object of type 'float'
Call stack:
  File "E:\Unknown-Horizons\unknown-horizons\run_uh.py", line 381, in <module>
    main()
  File "E:\Unknown-Horizons\unknown-horizons\run_uh.py", line 122, in main
    ret = horizons.main.start(options)
  File "E:\Unknown-Horizons\unknown-horizons\horizons\main.py", line 255, in start
    horizons.globals.fife.run()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\engine\engine.py", line 279, in run
    self.loop()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\engine\engine.py", line 296, in loop
    f()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\timer.py", line 112, in check_tick
    f(self.tick_next_id)
  File "E:\Unknown-Horizons\unknown-horizons\horizons\scheduler.py", line 95, in tick
    callback.callback()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\util\python\callback.py", line 48, in __call__
    return self.callback(*self.args, **self.kwargs)
  File "E:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\__init__.py", line 317, in tick
    self.handle_settlements()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\__init__.py", line 360, in handle_settlements
    self.log.info('%s %s', self, goal)
Message: '%s %s'
Arguments: (<horizons.ai.aiplayer.AIPlayer object at 0x07D72B70>, <horizons.ai.aiplayer.goal.donothing.DoNothingGoal object at 0x132C7370>)
--- Logging error ---
Traceback (most recent call last):
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 829, in format    return fmt.format(record)
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 569, in format    record.message = record.getMessage()
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
  File "E:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\goal\__init__.py", line 86, in __str__
    self.priority, self.__class__.__name__, self.sequence_number)
ValueError: Unknown format code 'd' for object of type 'float'
Call stack:
  File "E:\Unknown-Horizons\unknown-horizons\run_uh.py", line 381, in <module>
    main()
  File "E:\Unknown-Horizons\unknown-horizons\run_uh.py", line 122, in main
    ret = horizons.main.start(options)
  File "E:\Unknown-Horizons\unknown-horizons\horizons\main.py", line 255, in start
    horizons.globals.fife.run()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\engine\engine.py", line 279, in run
    self.loop()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\engine\engine.py", line 296, in loop
    f()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\timer.py", line 112, in check_tick
    f(self.tick_next_id)
  File "E:\Unknown-Horizons\unknown-horizons\horizons\scheduler.py", line 95, in tick
    callback.callback()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\util\python\callback.py", line 48, in __call__
    return self.callback(*self.args, **self.kwargs)
  File "E:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\__init__.py", line 317, in tick
    self.handle_settlements()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\__init__.py", line 354, in handle_settlements
    self.log.info('%s all further goals during this tick blocked by goal %s', self, goal)
Message: '%s all further goals during this tick blocked by goal %s'
Arguments: (<horizons.ai.aiplayer.AIPlayer object at 0x07D72B70>, <horizons.ai.aiplayer.goal.donothing.DoNothingGoal object at 0x132C7370>)
--- Logging error ---
Traceback (most recent call last):
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 829, in format    return fmt.format(record)
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 569, in format    record.message = record.getMessage()
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
  File "E:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\goal\__init__.py", line 86, in __str__
    self.priority, self.__class__.__name__, self.sequence_number)
ValueError: Unknown format code 'd' for object of type 'float'
Call stack:
  File "E:\Unknown-Horizons\unknown-horizons\run_uh.py", line 381, in <module>
    main()
  File "E:\Unknown-Horizons\unknown-horizons\run_uh.py", line 122, in main
    ret = horizons.main.start(options)
  File "E:\Unknown-Horizons\unknown-horizons\horizons\main.py", line 255, in start
    horizons.globals.fife.run()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\engine\engine.py", line 279, in run
    self.loop()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\engine\engine.py", line 296, in loop
    f()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\timer.py", line 112, in check_tick
    f(self.tick_next_id)
  File "E:\Unknown-Horizons\unknown-horizons\horizons\scheduler.py", line 95, in tick
    callback.callback()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\util\python\callback.py", line 48, in __call__
    return self.callback(*self.args, **self.kwargs)
  File "E:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\__init__.py", line 317, in tick
    self.handle_settlements()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\__init__.py", line 360, in handle_settlements
    self.log.info('%s %s', self, goal)
Message: '%s %s'
Arguments: (<horizons.ai.aiplayer.AIPlayer object at 0x07D72B70>, <horizons.ai.aiplayer.goal.donothing.DoNothingGoal object at 0x132C7370>)
--- Logging error ---
Traceback (most recent call last):
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 829, in format    return fmt.format(record)
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 569, in format    record.message = record.getMessage()
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
  File "E:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\goal\__init__.py", line 86, in __str__
    self.priority, self.__class__.__name__, self.sequence_number)
ValueError: Unknown format code 'd' for object of type 'float'
Call stack:
  File "E:\Unknown-Horizons\unknown-horizons\run_uh.py", line 381, in <module>
    main()
  File "E:\Unknown-Horizons\unknown-horizons\run_uh.py", line 122, in main
    ret = horizons.main.start(options)
  File "E:\Unknown-Horizons\unknown-horizons\horizons\main.py", line 255, in start
    horizons.globals.fife.run()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\engine\engine.py", line 279, in run
    self.loop()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\engine\engine.py", line 296, in loop
    f()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\timer.py", line 112, in check_tick
    f(self.tick_next_id)
  File "E:\Unknown-Horizons\unknown-horizons\horizons\scheduler.py", line 95, in tick
    callback.callback()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\util\python\callback.py", line 48, in __call__
    return self.callback(*self.args, **self.kwargs)
  File "E:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\__init__.py", line 317, in tick
    self.handle_settlements()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\__init__.py", line 354, in handle_settlements
    self.log.info('%s all further goals during this tick blocked by goal %s', self, goal)
Message: '%s all further goals during this tick blocked by goal %s'
Arguments: (<horizons.ai.aiplayer.AIPlayer object at 0x07D72B70>, <horizons.ai.aiplayer.goal.donothing.DoNothingGoal object at 0x132C7370>)
--- Logging error ---
Traceback (most recent call last):
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 829, in format    return fmt.format(record)
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 569, in format    record.message = record.getMessage()
  File "E:\Unknown-Horizons\python\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
  File "E:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\goal\__init__.py", line 86, in __str__
    self.priority, self.__class__.__name__, self.sequence_number)
ValueError: Unknown format code 'd' for object of type 'float'
Call stack:
  File "E:\Unknown-Horizons\unknown-horizons\run_uh.py", line 381, in <module>
    main()
  File "E:\Unknown-Horizons\unknown-horizons\run_uh.py", line 122, in main
    ret = horizons.main.start(options)
  File "E:\Unknown-Horizons\unknown-horizons\horizons\main.py", line 255, in start
    horizons.globals.fife.run()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\engine\engine.py", line 279, in run
    self.loop()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\engine\engine.py", line 296, in loop
    f()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\timer.py", line 112, in check_tick
    f(self.tick_next_id)
  File "E:\Unknown-Horizons\unknown-horizons\horizons\scheduler.py", line 95, in tick
    callback.callback()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\util\python\callback.py", line 48, in __call__
    return self.callback(*self.args, **self.kwargs)
  File "E:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\__init__.py", line 317, in tick
    self.handle_settlements()
  File "E:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\__init__.py", line 360, in handle_settlements
    self.log.info('%s %s', self, goal)
Message: '%s %s'
Arguments: (<horizons.ai.aiplayer.AIPlayer object at 0x07D72B70>, <horizons.ai.aiplayer.goal.donothing.DoNothingGoal object at 0x132C7370>)
```

Hope it could help...
Thanks a lot for the game by the way ;)

**Comment by jmdejong** [comment]
What were you doing when this crash occured? How did you install the game?

**Comment by flupke256** [comment]
The game has been installed from the official site yesterday, latest Windows version with installer, on my computer which is Windows 10 64 bits.
I think I was placing some buildings ( normal house, depot, ... ), when a freeze occured, and then a crash with the log.

**Comment by jakoch** [comment]
```
File "E:\Unknown-Horizons\unknown-horizons\horizons\ai\aiplayer\goal\__init__.py", line 86, in __str__
    self.priority, self.__class__.__name__, self.sequence_number)
ValueError: Unknown format code 'd' for object of type 'float'
```

Fixed with https://github.com/unknown-horizons/unknown-horizons/commit/e238de2
