### ISSUE TITLE
Segfault on start

### ISSUE THREAD

**Issue by arie-itecho** [unknown-horizons/unknown-horizons#2908]
The game segfaults when I run it. Here's what I got from gdb:

```
Starting program: /usr/bin/python3 ./unknown-horizons
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff3713830 in ?? ()
```

**Comment by arie-itecho** [comment]
OK, since I didn't get a reply on this issue yet, I decided to dig into the code myself.

I ran the project through my vscodium setup with the python fault finder enabled. The crash happens on line 109 of run_uh.py `import horizons.main`

Here's the output from the fault finder:
```
Fatal Python error: Segmentation fault

Thread 0x00007f2a2affd700 (most recent call first):
  File "/home/arie/.vscode-oss/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd.py", line 196 in _on_run
  File "/home/arie/.vscode-oss/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 162 in run
  File "/usr/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007f2a2b7fe700 (most recent call first):
  File "/usr/lib/python3.5/threading.py", line 297 in wait
  File "/usr/lib/python3.5/threading.py", line 549 in wait
  File "/home/arie/.vscode-oss/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/_vendored/pydevd/pydevd.py", line 168 in _on_run
  File "/home/arie/.vscode-oss/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 162 in run
  File "/usr/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007f2a2bfff700 (most recent call first):
  File "/home/arie/.vscode-oss/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/wrapper.py", line 286 in recv
  File "/home/arie/.vscode-oss/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 251 in _read_line
  File "/home/arie/.vscode-oss/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 263 in _on_run
  File "/home/arie/.vscode-oss/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 162 in run
  File "/usr/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007f2a38b15700 (most recent call first):
  File "/usr/lib/python3.5/threading.py", line 297 in wait
  File "/usr/lib/python3.5/queue.py", line 173 in get
  File "/home/arie/.vscode-oss/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 363 in _on_run
  File "/home/arie/.vscode-oss/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 162 in run
  File "/usr/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007f2a39356700 (most recent call first):
  File "/home/arie/.vscode-oss/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/ipcjson.py", line 113 in _buffered_read_line_as_ascii
  File "/home/arie/.vscode-oss/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/ipcjson.py", line 154 in _wait_for_message
  File "/home/arie/.vscode-oss/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/ipcjson.py", line 272 in process_one_message
  File "/home/arie/.vscode-oss/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/ipcjson.py", line 258 in process_messages
  File "/home/arie/.vscode-oss/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/wrapper.py", line 722 in process_messages
  File "/usr/lib/python3.5/threading.py", line 862 in run
  File "/usr/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 882 in _bootstrap

Thread 0x00007f2a39b57700 (most recent call first):
  File "/usr/lib/python3.5/threading.py", line 297 in wait
  File "/usr/lib/python3.5/threading.py", line 549 in wait
  File "/home/arie/.vscode-oss/extensions/ms-python.python-2019.4.12954/pythonFiles/lib/python/ptvsd/futures.py", line 122 in run_forever
  File "/usr/lib/python3.5/threading.py", line 862 in run
  File "/usr/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 882 in _bootstrap

Current thread 0x00007f2a3db95700 (most recent call first):
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 34 in <module>
  File "<frozen importlib._bootstrap>", line 222 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 665 in exec_module
  File "<frozen importlib._bootstrap>", line 673 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23 in <module>
  File "<frozen importlib._bootstrap>", line 222 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 665 in exec_module
  File "<frozen importlib._bootstrap>", line 673 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23 in <module>
  File "<frozen importlib._bootstrap>", line 222 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 665 in exec_module
  File "<frozen importlib._bootstrap>", line 673 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30 in <module>
  File "<frozen importlib._bootstrap>", line 222 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 665 in exec_module
  File "<frozen importlib._bootstrap>", line 673 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5 in <module>
  File "<frozen importlib._bootstrap>", line 222 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 665 in exec_module
  File "<frozen importlib._bootstrap>", line 673 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load
  File "<frozen importlib._bootstrap>", line 222 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 944 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63 in apport_excepthook
Segmentation fault (core dumped)
```

Any ideas?

**Comment by arie-itecho** [comment]
So I figured out how to do a backtrace in gdb. Here's the interesting part of the output:
```
#1  0x00007ffff486840c in ReadConfigFile(Configuration&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool const&, unsigned int const&) ()
   from /usr/lib/x86_64-linux-gnu/libapt-pkg.so.5.0
#2  0x00007ffff4867d97 in ReadConfigDir(Configuration&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool const&, unsigned int const&) ()
   from /usr/lib/x86_64-linux-gnu/libapt-pkg.so.5.0
#3  0x00007ffff48d29aa in pkgInitConfig(Configuration&) () from /usr/lib/x86_64-linux-gnu/libapt-pkg.so.5.0
#4  0x00007ffff4b5cc48 in ?? () from /usr/lib/python3/dist-packages/apt_pkg.cpython-35m-x86_64-linux-gnu.so
#5  0x00000000004ea10f in PyCFunction_Call ()
```

Any ideas on what I should be looking for?

**Comment by jmdejong** [comment]
How did you install unknown horizons? And how did you install fife and fifechan?

**Comment by arie-itecho** [comment]
I built fife and fifechan from the source according to the instructions in the uh wiki. I installed uh by running setup.py

**Comment by kyrios123** [comment]
I get the same problem

**Comment by LinuxDonald** [comment]
Guys what distro are you using? And fife/fifechan and uh lastest git version? Or last release version?

**Comment by kyrios123** [comment]
I use Solus it's a x86_64 distro with kernel 5.1.14
Python 3.6.9
fifengine 0.4.2 / fifechan 0.1.5, both built from the latest tarball.

**Comment by TimSoethout** [comment]
I have the same problem on OSX. Python 3.7.4.
After a lot of pain fifechan and fifengine from master.
Had to remove some build options, might influence this?

```
-  set(CMAKE_SWIG_FLAGS -fastdispatch -dirvtable -noproxydel -fastproxy -fastinit -fastunpack -fastquery -modernargs -nobuildnone -keyword -w511 -w473 -w404 -w314)
+  set(CMAKE_SWIG_FLAGS -fastdispatch -dirvtable -fastproxy -keyword -w511 -w473 -w404 -w314)

```

**Comment by gorgobacka** [comment]
> I built fife and fifechan from the source according to the instructions in the uh wiki. I installed uh by running setup.py

I did the same and also get a Segmentation fault.

**Comment by LinuxDonald** [comment]
Try lastest fife and fifechan. If it still happen open please an new tciket.
