### ISSUE TITLE
Crash when selecting only one swordman

### ISSUE THREAD

**Issue by TurtleMat** [unknown-horizons/unknown-horizons#2937]
The game crashes when I select one soldier and only one soldier. there is no problem when there is also a building in the selection, or when there are 2 soldiers. 

I tested that on 2 separate games.

OS : Linux mint 19.3
game instaled through standard repository (apt-get install )

console output : 

```
Traceback (most recent call last):
 File "/usr/lib/python2.7/dist-packages/horizons/gui/mousetools/selectiontool.py", line 129, in mouseReleased
    self.apply_select()
 File "/usr/lib/python2.7/dist-packages/horizons/gui/mousetools/selectiontool.py", line 151, in apply_select
    iter(selected).next().get_component(SelectableComponent).show_menu()
 File "/usr/lib/python2.7/dist-packages/horizons/component/selectablecomponent.py", line 94, in show_menu
    tabwidget = TabWidget(self.session.ingame_gui, tabs=tabs, active_tab=active_tab_index)
 File "/usr/lib/python2.7/dist-packages/horizons/gui/tabs/tabwidget.py", line 53, in __init__
    self.current_tab.ensure_loaded() # loading current_tab widget
 File "/usr/lib/python2.7/dist-packages/horizons/gui/tabs/tabinterface.py", line 163, in ensure_loaded
    self._setup_widget()
 File "/usr/lib/python2.7/dist-packages/horizons/gui/tabs/tabinterface.py", line 102, in _setup_widget
    self.init_widget()
 File "/usr/lib/python2.7/dist-packages/horizons/gui/tabs/overviewtab.py", line 106, in init_widget
    super(GroundUnitOverviewTab, self).init_widget()
 File "/usr/lib/python2.7/dist-packages/horizons/gui/tabs/overviewtab.py", line 50, in init_widget
    self.init_stance_widget()
 File "/usr/lib/python2.7/dist-packages/horizons/gui/tabs/overviewtab.py", line 96, in init_stance_widget
    stance_widget.init(self.instance)
 File "/usr/lib/python2.7/dist-packages/horizons/gui/widgets/unitoverview.py", line 43, in init
    self.toggle_stance()
 File "/usr/lib/python2.7/dist-packages/horizons/gui/widgets/unitoverview.py", line 72, in toggle_stance
    self.findChild(name=self.instance.stance.NAME).set_active()
AttributeError: 'Unit[1000023]' object has no attribute 'stance'

Traceback (most recent call last):
  File "/usr/games/unknown-horizons", line 380, in <module>
    main()
  File "/usr/games/unknown-horizons", line 190, in main
    ret = horizons.main.start(options)
  File "/usr/lib/python2.7/dist-packages/horizons/main.py", line 247, in start
    horizons.globals.fife.run()
  File "/usr/lib/python2.7/dist-packages/horizons/engine/engine.py", line 279, in run
    self.loop()
  File "/usr/lib/python2.7/dist-packages/horizons/engine/engine.py", line 286, in loop
    self.engine.pump()
  File "/usr/lib/python2.7/dist-packages/fife/fife.py", line 2716, in pump
    return _fife.Engine_pump(self)
RuntimeError: Caught a director exception
AL lib: (EE) alc_cleanup: 1 device not closed
```

**Comment by LinuxDonald** [comment]
What version of the game have you tested?

**Comment by TurtleMat** [comment]
Oh I just realised that --version works I probably did a typo earlier. 

version 2017.2; might be kind of outdated ! 

I installed the game through apt-get isntall though, is it to be expected that it's the 2017 version? 

Anyways, thanks for the quick answer and tahnks everyone for the good work !

**Comment by LinuxDonald** [comment]
Yeah the last one is 2019.1
But this version will get no new release. Because we are working to port it to the godot engine.

**Comment by TurtleMat** [comment]
yeah I'm building from the sources and I'll try to replicate the crash. Should I close the issue?

**Comment by LinuxDonald** [comment]
If you have the same bug with lastest git version you could post the crash report. But I think we had disable units on lastest version.

**Comment by TurtleMat** [comment]
hum, I got problems running setup.py. 

I'll try some more and see what happens.
