### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by Naoiph** [unknown-horizons/unknown-horizons#2942]
I started the game and it crashed. First time installing it.

We are very sorry for this and want to fix the underlying error.
In order to do this, we need the information from the logfile:
C:\Users\user\Documents\My Games\unknown-horizons\log\unknown-horizons-2020-05-11_11-50-16.log
Please give it to us via Github bug tracker, Discord or IRC; see http://unknown-horizons.org/support/
lib\\site-packages']
PATHSEP: ";" SEP: "\"
LD_LIBRARY_PATH: <undefined>
PATH: C:\Program Files\GLEAMviz\libs;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\System32\OpenSSH\;C:\Unknown-Horizons\python\Lib\site-packages\fife;C:\Users\IoanG\AppData\Local\Microsoft\WindowsApps;C:\Users\IoanG\AppData\Local\GitHubDesktop\bin
PYTHONPATH <undefined>
Python version: sys.version_info(major=3, minor=7, micro=0, releaselevel='final', serial=0)
Platform: Windows-10-10.0.18362-SP0
Using fife version 0.4.2, at least 0.4.2 required
Traceback (most recent call last):
  File "C:\Unknown-Horizons\unknown-horizons\run_uh.py", line 381, in <module>
    main()
  File "C:\Unknown-Horizons\unknown-horizons\run_uh.py", line 122, in main
    ret = horizons.main.start(options)
  File "C:\Unknown-Horizons\unknown-horizons\horizons\main.py", line 113, in start
    horizons.globals.fife = Fife()
  File "C:\Unknown-Horizons\unknown-horizons\horizons\engine\engine.py", line 46, in __init__
    self._setting = Settings(PATHS.USER_CONFIG_FILE, PATHS.SETTINGS_TEMPLATE_FILE)
  File "C:\Unknown-Horizons\unknown-horizons\horizons\engine\settings.py", line 39, in __init__
    self._settings_serializer.load(settings_file)
  File "C:\Unknown-Horizons\python\lib\site-packages\fife\extensions\serializers\simplexml.py", line 129, in load
    self._tree = ET.parse(self._file)
  File "C:\Unknown-Horizons\python\lib\xml\etree\ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "C:\Unknown-Horizons\python\lib\xml\etree\ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

**Comment by LinuxDonald** [comment]
Sorry that you have problems. But we dont support this version of UH anymore. We are working on an new version. That use now godot engine instand of fife. But we dont have yet an playable version of it.
https://github.com/unknown-horizons/godot-port
