### ISSUE TITLE
Crash On Windows 10

### ISSUE THREAD

**Issue by Tuxcoder81** [unknown-horizons/unknown-horizons#2951]
Discovered old settings file, auto-upgrading: 1 -> 38
Traceback (most recent call last):
  File "D:\Games\mainfiles\Unknown-Horizons\unknown-horizons\run_uh.py", line 381, in <module>
    main()
  File "D:\Games\mainfiles\Unknown-Horizons\unknown-horizons\run_uh.py", line 122, in main
    ret = horizons.main.start(options)
  File "D:\Games\mainfiles\Unknown-Horizons\unknown-horizons\horizons\main.py", line 171, in start
    horizons.globals.fife.init()
  File "D:\Games\mainfiles\Unknown-Horizons\unknown-horizons\horizons\engine\engine.py", line 171, in init
    self.cursor_images = {k: self.imagemanager.load(v) for k, v in cursor_images.items()}
  File "D:\Games\mainfiles\Unknown-Horizons\unknown-horizons\horizons\engine\engine.py", line 171, in <dictcomp>
    self.cursor_images = {k: self.imagemanager.load(v) for k, v in cursor_images.items()}
fife.fife.SDLException: _[SDLException]_ , SDL reported something bad :: Fatal Error when loading image into a SDL_Surface: Failed loading libpng16-16.dll: The specified module could not be found.

**Comment by LinuxDonald** [comment]
Sorry that you have problems. But we dont support this version of UH anymore. We are working on an new version. That use now godot engine instand of fife. But we dont have yet an playable version of it.
https://github.com/unknown-horizons/godot-port

**Comment by artism90** [comment]
There's a dependency issue. Did you only clone the repo? Try the official release installer for Windows, it provides everything needed (+ the right Python version) and hence should work out of the box: https://github.com/unknown-horizons/unknown-horizons/releases/download/2019.1/Unknown-Horizons-2019.1.214-Setup-VC15-x86.exe

Also, do not install the files inside a path with spaces in between, this is another typical cause of error.
