### ISSUE TITLE
iniciar o jogo

### ISSUE THREAD

**Issue by celcoder00** [unknown-horizons/unknown-horizons#2952]
Logging to b'C:\\Users\\Utilizador\\Documents\\My Games\\unknown-horizons\\log\\unknown-horizons-2021-01-17_11-04-50.log' and C:\Unknown-Horizons\unknown-horizons\fife.log
Discovered old settings file, auto-upgrading: 35 -> 38
Traceback (most recent call last):
  File "C:\Unknown-Horizons\unknown-horizons\run_uh.py", line 381, in <module>
    main()
  File "C:\Unknown-Horizons\unknown-horizons\run_uh.py", line 122, in main
    ret = horizons.main.start(options)
  File "C:\Unknown-Horizons\unknown-horizons\horizons\main.py", line 113, in start
    horizons.globals.fife = Fife()
  File "C:\Unknown-Horizons\unknown-horizons\horizons\engine\engine.py", line 46, in __init__
    self._setting = Settings(PATHS.USER_CONFIG_FILE, PATHS.SETTINGS_TEMPLATE_FILE)
  File "C:\Unknown-Horizons\unknown-horizons\horizons\engine\settings.py", line 46, in __init__
    self.upgrade_settings()
  File "C:\Unknown-Horizons\unknown-horizons\horizons\engine\settings.py", line 112, in upgrade_settings
    if self.get(module, setting_name, default=default_value) is default_value:
  File "C:\Unknown-Horizons\unknown-horizons\horizons\engine\settings.py", line 52, in get
    v = self._settings_serializer.get(module, name, default)
  File "C:\Unknown-Horizons\python\lib\site-packages\fife\extensions\serializers\simplexml.py", line 229, in get
    e_value = self.getValue(e_type,e_value)
  File "C:\Unknown-Horizons\python\lib\site-packages\fife\extensions\serializers\simplexml.py", line 162, in getValue
    return int(e_value)
ValueError: invalid literal for int() with base 10: 'True'

 Unknown Horizons has crashed.

We are very sorry for this and want to fix the underlying error.
In order to do this, we need the information from the logfile:
C:\Users\Utilizador\Documents\My Games\unknown-horizons\log\unknown-horizons-2021-01-17_11-04-50.log
Please give it to us via Github bug tracker, Discord or IRC; see http://unknown-horizons.org/support/
por favor ajudem...

**Comment by jmdejong** [comment]
I think there's something wrong with your settings file

You can find that file in `My Games\unknown-horizons\settings.xml`

If you don't mind resetting your settings then you can just delete that file and run Unknown Horizons again.
It will create a new settings file with all the default settings.

**Comment by celcoder00** [comment]
I think i have cleaned everything and mês download but dont works ...to
many error i think i give up realy

A dom, 17/01/2021, 13:35, J.M. de Jong <notifications@github.com> escreveu:

**Comment by LinuxDonald** [comment]
Delete old save games. Upgrade of save game don't work I think.

**Comment by celcoder00** [comment]
Thanks for the tip! i have already make that and i have made a new download
but with so many errors that i am thinking to give up of the game....makes
me very sad because i like it ...

Thomas Kowaliczek-Schmer <notifications@github.com> escreveu no dia
domingo, 17/01/2021 à(s) 14:01:

**Comment by LinuxDonald** [comment]
We are working on an new version of UH with the Godot engine but not yet playable.
https://github.com/unknown-horizons/godot-port

**Comment by celcoder00** [comment]
Ok, thanks. I will wait for the possibility of download im futur

Em dom., 17 de jan. de 2021 às 14:35, Thomas Kowaliczek-Schmer <
notifications@github.com> escreveu:
