### ISSUE TITLE
[BUG] TypeError: __init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by Lukas1818** [unknown-horizons/unknown-horizons#2954]
Direct after the start of the game I get a type TypeError. A window does apper for a short time, but it does not show anything.

OS: Manajro Linux (based on Arch)
[unknown horizons AUR-package](https://aur.archlinux.org/packages/unknown-horizons/) 2019.1-4
[fife AUR-package](https://aur.archlinux.org/packages/fife/) 0.4.2-3 with [fix](https://github.com/fifengine/fifengine/pull/1078/commits/cf295fd98a8fba080f6305c27be56d10ab7ce94d) for the [deprecated getchildren()](https://docs.python.org/3.9/whatsnew/3.9.html#removed)
```
$ unknown-horizons
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
Traceback (most recent call last):
  File "/usr/bin/unknown-horizons", line 381, in <module>
    main()
  File "/usr/bin/unknown-horizons", line 122, in main
    ret = horizons.main.start(options)
  File "/usr/lib/python3.9/site-packages/horizons/main.py", line 179, in start
    Entities.load(horizons.globals.db, load_now=False) # create all references
  File "/usr/lib/python3.9/site-packages/horizons/entities.py", line 64, in load
    cls.load_grounds(db, load_now)
  File "/usr/lib/python3.9/site-packages/horizons/entities.py", line 77, in load_grounds
    tile_sets = TileSetLoader.get_sets()
  File "/usr/lib/python3.9/site-packages/horizons/util/loaders/tilesetloader.py", line 72, in get_sets
    cls.load()
  File "/usr/lib/python3.9/site-packages/horizons/util/loaders/tilesetloader.py", line 65, in load
    cls.tile_sets = JsonDecoder.load(PATHS.TILE_SETS_JSON_FILE)
  File "/usr/lib/python3.9/site-packages/horizons/util/loaders/jsondecoder.py", line 40, in load
    return json.load(f, encoding="ascii", object_hook=_decode_dict)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

**Comment by LinuxDonald** [comment]
@jmdejong @artism90 could you both look at this and on the Fife Engine pr too please?

**Comment by jmdejong** [comment]
I have not yet tried it, but looking at the [python documentation](https://docs.python.org/3/library/json.html#json.loads) it should be safe just to remove this argument from `horizons/util/loaders/jsondecoder.py` line 40

**Comment by Lukas1818** [comment]
> I have not yet tried it, but looking at the [python documentation](https://docs.python.org/3/library/json.html#json.loads) it should be safe just to remove this argument from `horizons/util/loaders/jsondecoder.py` line 40

I tested it and the game start now. But if I start a new single player game, I get a new error now:
```
$ unknown-horizons 
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
Traceback (most recent call last):
 File "/usr/lib/python3.9/site-packages/fife/extensions/fife_timer.py", line 125, in updateEvent
    self._callback()
 File "/usr/lib/python3.9/site-packages/fife/extensions/pychan/tools.py", line 94, in real_callback
    callback(*args,**kwargs)
 File "/usr/lib/python3.9/site-packages/fife/extensions/pychan/events.py", line 194, in delayed_f
    f( event )
 File "/usr/lib/python3.9/site-packages/fife/extensions/pychan/events.py", line 374, in captured_f
    tools.applyOnlySuitable(self_ref().callbacks[group_name][event_name],event=event,widget=self_ref().widget_ref())
 File "/usr/lib/python3.9/site-packages/fife/extensions/pychan/tools.py", line 71, in applyOnlySuitable
    return func(*args,**kwargs)
 File "/usr/lib/python3.9/site-packages/horizons/gui/modules/singleplayermenu.py", line 119, in act
    self._mode.act(player_name, player_color)
 File "/usr/lib/python3.9/site-packages/horizons/gui/modules/singleplayermenu.py", line 223, in act
    horizons.main.start_singleplayer(options)
 File "/usr/lib/python3.9/site-packages/horizons/main.py", line 321, in start_singleplayer
    preloader.wait_for_finish()
 File "/usr/lib/python3.9/site-packages/horizons/util/preloader.py", line 82, in wait_for_finish
    if self.isAlive():
AttributeError: 'PreloadingThread' object has no attribute 'isAlive'

Unknown Horizons exited uncleanly via SIGINT
```

The isAlive() function is also deprecated and was change to is_alive().
>The isAlive() method of threading.Thread has been removed. It was deprecated since Python 3.8. Use is_alive() instead. (Contributed by Dong-hee Na in bpo-37804.)

If I also change this, I can to play the game.

**Comment by LinuxDonald** [comment]
@jmdejong could you maybe an look on this needed changes and commit them please?

**Comment by LinuxDonald** [comment]
@Lukas1818 is that now fixed or are you getting still an crash/error?

**Comment by jmdejong** [comment]
I encountered the same error (about the 'encoding' arg) when I tried to run it and that was fixed with the PR

**Comment by Lukas1818** [comment]
> @Lukas1818 is that now fixed or are you getting still an crash/error?

No, I did not get a crash anymore.
While I had make the PR, I had already check this.
