### ISSUE TITLE
Could not find a matching screen mode for the values given!

### ISSUE THREAD

**Issue by demanuPL** [unknown-horizons/unknown-horizons#2958]
trying to run through Xwayland after changing resoluton to 1920x1080 results this:

`Traceback (most recent call last):
  File "/app/bin/unknown-horizons", line 381, in <module>
    main()
  File "/app/bin/unknown-horizons", line 122, in main
    ret = horizons.main.start(options)
  File "/app/lib/python3.9/site-packages/horizons/main.py", line 171, in start
    horizons.globals.fife.init()
  File "/app/lib/python3.9/site-packages/horizons/engine/engine.py", line 152, in init
    self.engine.init()
fife.fife.NotSupported: _[NotSupported]_ , This action was not supported :: Could not find a matching screen mode for the values given!
`

when I'm wiping out all my setting games run in windowed mode in default resolution

**Comment by benjaminhampe** [comment]
On windows the high dpi awareness is not working or is the bug. Meaning windows scales stuff up. A 1024x768 is much larger than expected. Thatswhy stuff like 1080p does not work even on 3k screens like surface pro. And the game looks more ugly due to unwanted scaling then it could.

Make it aware using a resource .rc embedded manifest (using a resource compiler windres.exe or similar)

app.manifest is a file right next to resource.rc:

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>

<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <!-- Supports Windows Vista / Server 2008 -->
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/>
      <!-- Supports Windows 7 / Server 2008 R2 -->
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
      <!-- Supports Windows 8 / Server 2012 -->
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
      <!-- Supports Windows 8.1 / Server 2012 R2 -->
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
      <!-- Supports Windows 10 -->
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
    </application>
  </compatibility>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false"/>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <dependency>
    <dependentAssembly>
      <assemblyIdentity type="Win32" name="Microsoft.Windows.Common-Controls" version="6.0.0.0" processorArchitecture="*" publicKeyToken="6595b64144ccf1df" language="*"/>
    </dependentAssembly>
  </dependency>
  
  <!-- Supports High DPI aware app -->
	<asmv3:application xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
		<asmv3:windowsSettings
		 xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
		<dpiAware>True/PM</dpiAware>
		</asmv3:windowsSettings>
	</asmv3:application>

</assembly>
```



**resource.rc**

```
#include <windows.h>
#include "resource.h"

aaaa ICON "app.ico"

// Application manifest.
CREATEPROCESS_MANIFEST_RESOURCE_ID RT_MANIFEST "app.manifest"

1 VERSIONINFO
FILEVERSION     1,0,0,0
PRODUCTVERSION  1,0,0,0
BEGIN
  BLOCK "StringFileInfo"
  BEGIN
    BLOCK "080904E4"
    BEGIN
      VALUE "CompanyName", "LLC"
      VALUE "FileDescription", "Live64_qt6"
      VALUE "FileVersion", "26.04"
      VALUE "InternalName", "Live64_qt6"
      VALUE "LegalCopyright", "Donationware"
      VALUE "OriginalFilename", "AbentonLive64_qt6"
      VALUE "ProductName", "Live64_qt6"
      VALUE "ProductVersion", "26.04"
    END
  END

  BLOCK "VarFileInfo"
  BEGIN
    VALUE "Translation", 0x809, 1252
  END
END
```

resource.h

`#define aaaa                    101`

Another option is to use Win32api, i guess that is how Qt does it.

**Comment by jakoch** [comment]
- the user is trying to set a specific screen resolution _using Xwayland_
- the fife sdl/opengl backend can't find the requested screen mode
- windowed mode with default resolution works ok

```
1. main()
2. horizons.main.start()
3. globals.fife.init()
4. engine.init()
5. fife.fife.NotSupported: Could not find a matching screen mode for the values given!
```

This needs a bugfix on FIFE to handle the missing screen modes in a better way.
