### ISSUE TITLE
ImportError: cannot import name 'fife' from 'fife'

### ISSUE THREAD

**Issue by jkpj22** [unknown-horizons/unknown-horizons#2959]
Hello, I get this error when I try to run the game by: 
`./run_uh.py`

```
Traceback (most recent call last):
  File "/home/jkpj/unknown-horizons/./run_uh.py", line 381, in <module>
    main()
  File "/home/jkpj/unknown-horizons/./run_uh.py", line 109, in main
    import horizons.main
  File "/home/jkpj/unknown-horizons/horizons/main.py", line 41, in <module>
    from fife import fife as fife_module
ImportError: cannot import name 'fife' from 'fife' (/home/jkpj/.local/lib/python3.10/site-packages/fife/__init__.py)
```

Can you please help to debug this? I am not developer, I tried to google it, I found some info about circular dependencies, but I don't know what to do about it.

**Comment by LinuxDonald** [comment]
Have you fife and fifechan installed?

**Comment by Raynergy-svg** [comment]
Run this command in terminal, 

"pip install fife" 

Seems that you didn't install all requirements.
